### PR TITLE
Allow custom import of db and files in provider interface (ddev pull)

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

Discussed in https://github.com/drud/ddev/pull/3223 thanks to @jonaseberle 

The `ddev pull` provider interface can be a little too inflexible. It assume one database, for example, when there might be more than one. It also assumes that you don't know where the files are going to go, and you might want to send them somewhere else. 

## How this PR Solves The Problem:

Allow `db_import_command` and `files_import_command` to take over the job of actually doing the import.

## Manual Testing Instructions:

- [x] Experiment with the updated `localfile.yaml.example`, which demonstrates the new usage.

## Automated Testing Overview:

TestLocalfilePull now tests these feature

## Related Issue Link(s):

Replaces #3223  

## Release/Deployment notes:

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3373"></a>

### CODE REVIEW

**Comment by rfay** [comment]
This can be tested in gitpod using https://gitpod.io/#https://github.com/drud/ddev/pull/3223

Artifacts can be downloaded for local experimentation at https://github.com/drud/ddev/actions/runs/1469618009

**Comment by jonaseberle** [comment]
That is great! Thank you so much! 
I tested locally.

It absolutely stays as easy as it has been before while still allowing for more complex setups.

Functionally I wasn't able to make it misbehave in any way. `--skip-db` / `--skip-files` / `--skip-import` behave as before/expected, too.

----

Some docs/example additions and improvable command output I noticed so far (nothing serious or blocking - I am happy to go through it and do PRs):

_command output:_
- When giving a custom `_pull_command`, it still outputs `Database/Files downloaded to: /.../.ddev/.downloads/...` which might not be what actually happened in that custom command.

_docs:_
- In order to have a step do nothing but still prevent the default import (for example if the `_pull_command` already downloaded files to the final locations), add a `_import_command` without the `command:` declaration.

**Review by jonaseberle — APPROVED** [review]

**Comment by rfay** [comment]
Thanks @jonaseberle - 

I didn't understand the comment 

> command help text: misses descriptions for --skip*/-y

because

```
$ ddev pull localfile -h
Pull with localfile

Usage:
  ddev pull localfile [flags]

Examples:
ddev pull localfile
ddev pull localfile -y
ddev pull localfile --skip-files -y

Flags:
  -h, --help                help for localfile
  -y, --skip-confirmation   Skip confirmation step
      --skip-db             Skip pulling database archive
      --skip-files          Skip pulling file archive
      --skip-import         Downloads file and/or database archives, but does not import them

Global Flags:
  -j, --json-output   If true, user-oriented output will be in JSON format.
```

**Comment by jonaseberle** [comment]
Oh, haven't noticed that it is there already when called like that.

I was looking for it with `ddev pull --help` or `ddev help pull`.

**Pull request merged**
