### PR TITLE
chore: Capitalized WordPress

### PR DESCRIPTION
**Pull request by JulienMelissas**
Looks like an awesome project! Some people might see WordPress capitalized incorrectly and pass over the project or something, this fixes it to the correct capitalization.

### CODE REVIEW

**Comment by rfay** [comment]
I found a couple of other Wordpress usage problems, including a couple of "worpress" :) and fixed them up in https://github.com/drud/ddev/pull/600

**Comment by rickmanelius** [comment]
Hi @JulienMelissas. First, thank you for taking the time to surface this. We/I should know better given some of the feedback from the WordPress devs at my previous agency. It was certainly not intended to be disrespectful/careless and we're making strides to improve our overall documentation and consistency across the board. Heck, we're also trying to re-evaluate if we are going to standardize on DDEV, ddev, or Ddev... Thanks again!

**Comment by JulienMelissas** [comment]
Hey @rickmanelius & @rfay! Thanks for the thorough response, it's much appreciated. I assumed there might be some more instances, but I just popped in to fix the most obvious ones (it's easy with GH's editor). I appreciate you getting to the others and I'm always happy to bring this up! It's a small detail that can make it or break it for a lot of WP developers who've been doing this for a while. Almost like "who's done their research?" Again, I appreciate it, and it looks like a cool project that I hope I get to play with soon!

**Comment by rfay** [comment]
We look forward to your input. We confess to being a bit more naive about WP than we'd wish, being a bunch of old Drupalistas. So we'd love to hear anything that you run across.

**Pull request merged**
