### PR TITLE
[docs] Bump mkdocs-material for possible improved search behavior

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

For docs, mkdocs-material has hopefully improved handling of search results that are inside tabs, etc. 

* https://github.com/squidfunk/mkdocs-material/issues/4125

But... I don't think what he shows in https://github.com/squidfunk/mkdocs-material/issues/4125#issuecomment-1374882924 has made it into current versions. But I don't think it hurts to update here. 

## Manual Testing Instructions

Review docs at https://ddev--4670.org.readthedocs.build/en/4670/

### CODE REVIEW

**Review by mattstein — APPROVED** [review]
The updated callout styles are nice, but I’m not seeing that this impacts search. After reading through [that conversation](https://github.com/squidfunk/mkdocs-material/issues/4125) I’m realizing that [`navigation.instant`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading) unfortunately [needs to be disabled](https://github.com/squidfunk/mkdocs-material/issues/4125#issuecomment-1204510033), though—my mistake in 4fb330895db2e5ecf84fd2651615c9a8b568655e.

**Comment by rfay** [comment]
@mattstein want me to disable navigation.instant in this PR?

**Comment by mattstein** [comment]
If you don’t mind that’d be great @rfay. Otherwise I can follow up with a separate PR.

**Comment by rfay** [comment]
I removed navigation.instant.

**Pull request merged**
