### PR TITLE
[docs] Minor typo in performance.md [skip ci]

### PR DESCRIPTION
**Pull request by lolli42**

### CODE REVIEW

**Review by rfay — COMMENTED** [review]
I'm unable to detect the difference in your proposal. Can you please say what it is?

**Comment by lolli42** [comment]
Whitespace after a comma

**Comment by lolli42** [comment]
`with vagrant on macOS,and you already have`
->
`with vagrant on macOS, and you already have`

Sorry for hard to spot no-brainer patch ;) But hey, a contribution ;)

**Comment by rfay** [comment]
Thanks!

**Pull request merged**
