### PR TITLE
Use php8 for Laravel

### PR DESCRIPTION
**Pull request by weitzman**
Laravel 9, just released, requires PHP 8.0+

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3588"></a>

### CODE REVIEW

**Comment by tyler36** [comment]
Confirmed. 

Laravel 9 [requires PHP 8.0](https://laravel.com/docs/8.x/releases#support-policy)

**Comment by tyler36** [comment]
I actually got on this this mornign and didn't get a chance to submit a PR. Great job @weitzman !

**Comment by rfay** [comment]
Thanks so much for catching this! I modified to just have project type laravel automatically use php8.0. Please test and see if you approve.  Artifacts are at https://github.com/drud/ddev/runs/5159143580?check_suite_focus=true or you can test with gitpod https://gitpod.io/#https://github.com/drud/ddev/pull/3588

**Comment by rfay** [comment]
Rebased, manually tested, seems to work fine. `php_version: 8.0` in the .ddev/config.yaml.

**Pull request merged**
