### PR TITLE
Web environment variables - allow spaces, fixes #4220

### LINKED ISSUE #4220: (web) environment variables cannot contain spaces
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/AronNovak/044136fd2eed011e80bbe4c03fbd89e0

### Expected Behavior

I should be able to expose the commit message to the container this way.

### Actual Behavior

Results in a global config where all spaces are trimmed.
So for instance:
```
web-environment=[TRAVIS_COMMIT_MESSAGE=Mergepullrequest#3388fromGizra/3387-deploy-notification-test
```

Which is suboptimal.

### Steps To Reproduce

Try to do (we use it inside theCI env):
`ddev config global --web-environment-add="TRAVIS_COMMIT_MESSAGE=$TRAVIS_COMMIT_MESSAGE"`

Or alternatively:
`ddev config global --web-environment-add="TRAVIS_COMMIT_MESSAGE=the commit message"`

`ddev config global --web-environment-add="TRAVIS_COMMIT_MESSAGE='the commit message'"`

`ddev config global --web-environment-add=TRAVIS_COMMIT_MESSAGE="the commit message"`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AronNovak**
## The Problem/Issue/Bug:
#4220 

## How this PR Solves The Problem:
Instead of eliminating all the spaces, it just eliminates trailing + leading spaces.

## Manual Testing Instructions:
See the issue.

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4221"></a>

### CODE REVIEW

**Comment by rfay** [comment]
So far it looks like there's just some extra space added, see TestConfigSetValues. You can run that manually and get it going...

**Comment by rfay** [comment]
Rebased. I hope you'll be able to take a look soon, thanks!

**Comment by rfay** [comment]
Should be ready to go when tests are green.

**Comment by AronNovak** [comment]
@rfay Thanks a lot for taking care of the last touches!

**Pull request merged**
