### PR TITLE
Adding ddev logo to readme.

### PR DESCRIPTION
**Pull request by cyberswat**
This adds the ddev logo to the readme file in a prominent location.

### CODE REVIEW

**Comment by beeradb** [comment]
(minor) feels like another line of spacing between the logo and the badges would give it more room to breath

**Comment by cyberswat** [comment]
@beeradb I agree but already felt dirty adding a paragraph and image tag into a markdown file.  I added a markdown based horizontal rule that kind of accomplishes the same.  See if that works.

**Comment by cyberswat** [comment]
This pull request would complete https://github.com/drud/ddev/issues/306

**Comment by cyberswat** [comment]
@beeradb it is a properly sized image.  It's a good idea when using html to specify width and height because it helps browsers understand how to render it before the image loads.

I'll remove the formatting and left align it.

**Pull request merged**
