### PR TITLE
Docs: Escape asterisks in glob patterns

### PR DESCRIPTION
**Pull request by mootari**
## The Problem/Issue/Bug:
The documentation uses glob patterns with asterisks in several places. In Markdown, asterisks have to be escaped if they need to be rendered verbatim.

## How this PR Solves The Problem:

Escapes asterisks in glob patterns in ~~the document "Extending and Customizing Environments"~~ all Markdown documents below `/docs`.

Note: There are likely more occurences in other files.

### CODE REVIEW

**Review by rfay — APPROVED** [review]
Perfect, thanks so much!

**Comment by mootari** [comment]
Some asterisks already rendered properly without being escaped (e.g. in a headline), likely because they had no terminating asterisk in the same block. I'd recommend to still be consistent and escape all occurrences.

**Comment by rfay** [comment]
Could you please push another commit to fix all of them? Thanks!

**Comment by mootari** [comment]
> Could you please push another commit to fix all of them?

Done! I only checked for `.*` and `*.` (separately), but imo this should cover all instances.

At some point someone will have to do another pass over the docs to wrap plain text file names/patterns and variables as inline code (after which the escaping won't be necessary any longer).

**Comment by rfay** [comment]
And of course I'd love it if you'd sign up for that :)

**Pull request merged**
