### PR TITLE
Try docker-compose 2.5.1 to test functionality

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

compose 2.5.1 has probably fixed https://github.com/docker/compose/issues/9428

## How this PR Solves The Problem:

Run a set of tests to see if they succeed.

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3851"></a>

### CODE REVIEW

**Comment by jonaseberle** [comment]
I have some problems.

`docker ps -a` shows the `...-web` container up but `ddev ssh` shows:
```
$ ddev ssh
service "web" is not running container #1
Failed to ddev ssh web: exit status 1
```
`docker exec ...-web ls` works.


Sorry, don't have time to investigate now. It works with 1.19.2

**Comment by jonaseberle** [comment]
Works with previous commit 85f1ad71b0e04e429b5aa97a376454f7889d3e18

**Comment by rfay** [comment]
Thanks so much for testing. I'm not having any trouble at all with `ddev ssh` or `ddev ssh -s db`.  (arm64 macos). Seems to work OK on gitpod too, https://gitpod.io/#https://github.com/drud/ddev

**Comment by jonaseberle** [comment]
Seems to be my project names containing `-` and `.` again:

```
mkdir a-b.c
cd a-b.c
ddev start
ddev ssh
```

**Comment by rfay** [comment]
Oh my goodness.

**Comment by rfay** [comment]
I guess we need a test for that.

**Comment by rfay** [comment]
Trying to find where that was worked. I see https://github.com/docker/compose/issues/8855 but I had closed that. Not finding the issue in the ddev queue, or issue opened by you. I found the issue that dots don't work in project names for PhpStorm.

**Comment by rfay** [comment]
Also... using your recreation from https://github.com/drud/ddev/pull/3851#issuecomment-1132937760 I'm not having any trouble on WSL2, but I can recreate in gitpod, so I imagine it's a docker-ish thing maybe. 

On gitpod it demos easily:
```
ddev delete -Oy d9simple && ddev poweroff
mkdir -p ~/tmp && cd ~/tmp
mkdir a-b.c
cd a-b.c
ddev config --auto
ddev start
ddev ssh
```

**Comment by rfay** [comment]
I can also recreate with that same sequence on WSL2 with docker running inside the WSL2 distro.

**Comment by rfay** [comment]
I see 
* https://github.com/docker/compose/issues/8881

**Comment by rfay** [comment]
* https://github.com/compose-spec/compose-go/pull/197
What they did was just remove the dot.

**Comment by rfay** [comment]
* https://github.com/drud/ddev/pull/3859

**Pull request merged**
