### PR TITLE
#3456 - add project type "node" and configure nginx as reverse proxy for it

### PR DESCRIPTION
**Pull request by hchonov**
This PR aims at providing a solution for running Node.js apps behind a proxy with DDEV. 

See https://github.com/drud/ddev/issues/3456

## The Problem/Issue/Bug:
Currently it is not possible to use ddev to start directly a project unless one configures a custom nginx config with reverse proxy settings.

## How this PR Solves The Problem:
1. A new project type "node" is being added that can be specified in the .ddev/config.yml.
2. The new project type comes without any configuration, but a dedicated nginx config preconfigured as reverse proxy.
3. The reverse proxy will initially forward to https://localhost:3000 so you would have to start your application on that port. This can be changed later, but should be sufficient for an initial implementation.

Further with the current changes it is no longer required to set `disable_settings_management: true` in the config.yml of the project.
## Manual Testing Instructions:
The following config.yml configuration should be enough to run a NextJS app using express:

```
name: my-node-app
type: node
webserver_type: nginx-fpm
nodejs_version: "16"
omit_containers: ['db', 'dba']
hooks:
  post-start:
    - exec: NODE_ENV=development PORT=3000 node server.js
```

If you are using express-ipfilter you might need something like this to allow the request initiator's address after a check that it is running on a dev environment:
```
    if (dev) {
      return IpFilter(allowedIpList, {
        mode: 'allow',
        // Allow the ddev private addresses.
        trustProxy: 'uniquelocal',
      })(req, res, _next);
    }
```
 
## Automated Testing Overview:
No test coverage yet.

## Related Issue Link(s):
https://github.com/drud/ddev/issues/3456

## Release/Deployment notes:
No.

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4006"></a>

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
This is interesting thinking. I hadn't thought of node being a project type, which may be a reasonable thing. But... aren't there going to be many different types of project that would use node?

Also, nothing you're doing here launches nodejs or tells it where it should be running. The nginx config just assumes it can pass things off to node.

We'd want to start nodejs in supervisord I'd imagine, so add another conf file to the supervisor config?

**Comment by hchonov** [comment]
> This is interesting thinking. I hadn't thought of node being a project type, which may be a reasonable thing. But... aren't there going to be many different types of project that would use node?

With my PR I am covering the use case of a NextJS decoupled app that lives in its own repository and retrieves the data from the backend via APIs. I think that we can start with one use case and go further adding support for other use cases if you agree. If needed we can introduce the type nextjs instead of node in order to make it more clear that we currently only support nextjs apps, but since probably the way of starting applications might be pretty similar I am not sure if it worth it to make the separation?

> Also, nothing you're doing here launches nodejs or tells it where it should be running. The nginx config just assumes it can pass things off to node.

If you look at the config.yml the first implementation was intending that the developers take care of starting the node app via a post-start hook. My thought here was that we do not have a project that has a standard entry point like index.php, but everyone wants to start their app in a different way. 

> We'd want to start nodejs in supervisord I'd imagine, so add another conf file to the supervisor config?

I agree and I've pushed a new commit, and now instead of using a post-start hook we can define the command that the supervisor should use.

Now it is possible to start the node app with ddev using the following `config.yml`:
```
name: my-node-app
type: node
webserver_type: nginx-fpm
omit_containers: ['db', 'dba']
nodejs_version: "16"
web_environment:
  - NODE_ENV=development
  - PORT=3000
node_cmd: node server.js --prefix /var/www/html
```

where the environment variables that I am setting ared used by my `server.js`.

**Comment by rfay** [comment]
Why shouldn't we just add nginx proxying of port 3000 to all projects? Super simple thing to do. Why add a new project type for that?

What I'd prefer to do here is:
1. A PR to proxy port 3000 using both HTTP_EXPOSE and HTTPS_EXPOSE, and solve https://github.com/drud/ddev/issues/4032 by adding NODE_EXTRA_CA_CERTS. 
2. A ddev add-on that explores this territory as well as we can, to try to find out what the "general" solution for nodejs is. Already https://github.com/drud/ddev-browsersync and https://github.com/torenware/ddev-viteserve are exploring this territory, but there's more to be done.

**Comment by rfay** [comment]
I so appreciate your inspiration thinking about this. I think we'll do as I suggested - 
* https://github.com/drud/ddev/pull/4057

Could you please review that? Please try it out and say what you think is missing. I really want to be able to provide first-class nodejs support for all the many ways it's used.

Closing this in favor of #4057 - which you absolutely inspired.

**Pull request closed without merging**
