### PR TITLE
prebuild is getting deprecated

### PR DESCRIPTION
**Pull request by shaal**
Details: https://github.com/gitpod-io/gitpod/issues/4205

## Release/Deployment notes:

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3032"></a>

### CODE REVIEW

**Review by rfay — APPROVED** [review]
Thanks! And prebuild didn't seem to actually do anything anyway. You still have to wait and wait for it to do it all.

**Comment by shaal** [comment]
@rfay AFAIK, prebuilds do run in the background, after you push a branch or open a PR.
If you open that new workspace before the prebuild finished, you will see the prebuild process itself.
No?

**Comment by rfay** [comment]
I haven't found at any time that the prebuild/init stuff has completed before I try clicking the link in the PR, even if it's hours later.

**Comment by shaal** [comment]
That sounds like a bug.

**Comment by rfay** [comment]
Yes, https://github.com/gitpod-io/gitpod/issues/4054

**Pull request merged**
