### PR TITLE
add Mailhog note for Laravel users

### PR DESCRIPTION
**Pull request by tyler36**
## The Problem/Issue/Bug:
The documents [Email Capture and Review](https://ddev.readthedocs.io/en/stable/users/developer-tools/#email-capture-and-review) documents seem misleading for Laravel projects.

They state that mailhog "will not intercept emails if your application is configured to use SMTP ...", although later it talks about configuration.

## How this PR Solves The Problem:
This PR adds specific Laravel `.env` settings to configure Mailhog email interception.

## Manual Testing Instructions:
- Create a Laravel project
- Config DDEV with default settings
- Update the `.env` file with the settings
- Attempt to send mail

A [demo project](https://github.com/tyler36/ddev-smpt-mailhog) was created for testing purposes.

## Release/Deployment notes:

- I debated about updating the quickstart guide or adding the config here. 
- I'm not sure if other frameworks have a similar "simple steps" that could help simplify this section or be delegated to quick start guides.

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3352"></a>

### CODE REVIEW

**Comment by rfay** [comment]
Interested in checking out magento2? I'm not even certain about WordPress. Certainly not certain about shopware6.

**Comment by tyler36** [comment]
Never used magento2.

I have a Laravel background with year-ish of Drupal.

**Comment by tyler36** [comment]
Are trying to trick me into testing the Magento Quickstart guide? 😉

**Comment by rfay** [comment]
No tricking going on here! It's straight-up asking! People have been using magento and magento2, maybe lots of them... but I'm a complete novice at both, and rarely hear back about the poverty of my novice-ness :)

**Comment by tyler36** [comment]
I had a quick look but they want me to create an account just to download the code. 

@cmuench might be able to help. He said in the [Organize DDEV-Local Advisory Group](https://github.com/drud/ddev/issues/2057) issue he's into Magento. (Obviously, my mention is in no way an obligation or commitment)

**Comment by rfay** [comment]
Even I was able to create an account!

**Comment by cmuench** [comment]
@tyler36 @rfay If you need to test anything in Magento1 or Magento 2. Let me know. I've been working with with Magento since 2008.

**Comment by rfay** [comment]
Thanks @cmuench - It can always be improved. But here I was wondering if extra instructions were required in the quickstart or the mailhog docs for mail capture on magento/magento2 like @tyler36 pointed out were needed for laravel.

**Review by rfay — APPROVED** [review]
Thanks for this!

**Pull request merged**
