### PR TITLE
adds install script

### PR DESCRIPTION
**Pull request by tannerjfco**
## The Problem:
#98 OP. We want one of those popular install scripts for our project.
## The Fix:
This introduces an install script. It detects the OS to determine the asset to download, verifies checksum, and installs ddev, prompting user for sudo if needed.
## The Test:
Run this one-liner:
```
curl https://raw.githubusercontent.com/tannerjfco/ddev/install-script/install.sh | bash
```

## Automation Overview:

#98 was flagged as needing tests, but I'm not sure what tests we would need to write for this. 

## Related Issue Link(s):
#98 OP
## Release/Deployment notes:

To use the `/releases/latest` end point, we won't be able to flag our releases as Pre-releases in GitHub, as this endpoint omits pre-releases. This suggests to me that pre-release is primarily intended for the purpose of release candidates, and not early development releases. This is a little annoying, but I think our use of SemVer is sufficient to indicate that this is a development release. We can also add a note in readme if we're worried about it. This is just a bit of oddity during our early dev phase, once we reach 1.x this ceases to become a concern.

### CODE REVIEW

**Comment by rickmanelius** [comment]
I think this would be helpful to get another reviewer on as well. @rfay or @beeradb, are either of you game?

**Comment by rickmanelius** [comment]
I plan on testing this with my personal laptop (hopefully tonight).

**Comment by rfay** [comment]
Oh btw, it didn't put the root user on ddev in /usr/local/bin, which I was worrying about. So the only issue with using sudo is it's not normally required on OSX.

**Comment by rfay** [comment]
I also tested this on linux and it worked fine.

I do have one request though: Could we change the script name to install_ddev.sh ? Otherwise it's just another anonymous where-did-it-come-from script laying around.

**Comment by tannerjfco** [comment]
I renamed the script as requested. I also updated to not sudo if we don't need to for moving to /usr/local/bin.

**Comment by tannerjfco** [comment]
@rickmanelius docker install warning added

**Pull request merged**
