### PR TITLE
Experimental support for Apple Silicon M1 (darwin_arm64), fixes #2338

### LINKED ISSUE #2338: Support darwin/arm64 on Apple Silicon
The announcement was made this week that macOS and mac hardware are going to switch to ARM chips.

This has major impact on DDEV-Local. We'll want to be prepared for the new hardware before it is released in Fall, 2020

- [x] Obtain ARM macOS hardware for testing with macOS 11 Big Sur beta
- [x] Prepare build techniques for Docker images (#2454)
- [x] Improve build techniques to build ddev fat binary with ARM (#2474)
- [x] Inform ddev-live cli build process of required changes
- [x] Make sure that all related resources are updated for ARM
    - [x] Docker Desktop
    - [x] mkcert (https://github.com/FiloSottile/mkcert/pull/284) - we may have to fork, as mkcert maintainer hasn't been responsive lately.

In order to have DDEV-Local ready for before new hardware comes out, we should
- [x] Subscribe to the [Universal App Quick Start Program](https://developer.apple.com/programs/universal/), which costs $500 and includes a loaner ARM machine which is to be returned after the program is complete.

Related: #2322 is about building binary and docker images, and it may come sooner.

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

darwin_arm64 provisional support. This is rough and needs work yet, but here it is.

https://twitter.com/randyfay/status/1337208925289005062

Congrats to @dennisameling for laying all the groundwork for this!

## TODO

- [x] Only use gotip for the darwin_arm64 build (figure out how to do it). That's not a very stable way to do things! golang v1.16 will come out in Jan or Feb
- [x] Production build in circleci (and then github actions)
- [x] Signing and notarizing
- [x] mkcert darwin_arm64 version, may need to be notarized. If darwin_arm64 is done, change install_ddev.sh
- [x] Use of golang-build-container is error-prone
- [ ] Cleaner recipe for sign and notarize (currently copy-paste)

### CODE REVIEW

**Comment by mglaman** [comment]
@rfay do you know how to install Docker Edge directly? because it now ships as a combined package, and the default Docker won't install to be able to turn on Edge.

**Comment by rfay** [comment]
@mglaman There is no more edge; they just discontinued it. The Docker M1 Tech Preview link is in (failed) release https://github.com/drud/ddev/releases/tag/v1.17.0-alpha1 - I'll try again in a few minutes. Somehow dropped some lines out of the Makefile.

**Comment by rfay** [comment]
@mglaman it's ready for you to test, full instructions at https://github.com/drud/ddev/releases/tag/v1.17.0-alpha1

**Comment by mglaman** [comment]
So close!

```
ddev start
Starting {PROJECT}..
Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate has expired or is not yet valid
Failed to start people: exit status 1
```

**Comment by rfay** [comment]
Just experiment with `docker pull`, for example `docker pull ubuntu` to figure this out. I haven't seen this.  Just tested and saw nothing of the kind. And I don't believe this has anything to do with docker desktop. Is it possible you have  an odd docker client binary laying around, not the one that ships with the tech preview?

**Pull request merged**
