### PR TITLE
WSL2: Manage hosts on the Windows side, fixes #3818

### LINKED ISSUE #3818: `ddev hostname` should edit both WSL2 and Windows hosts file when used
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

_No response_

### Current Behavior

When using DDEV inside WSL and starting a new ddev project the first time ddev adds entries in the /etc/hosts file of the system to ensure the project.ddev.site domain can be resolved locally.
This does not work well on WSL as ddev is currently editing the hosts file inside WSL which is not exposed to the windows host, so accessing the website via a browser on the host system is not possible.
Additionally the WSL hosts file will be regenerated on every WSL start to pepresent the state of the windows one.

DDEV warns you about this fact by outputting:

```text
You are on WSL2, so should also manually execute 'sudo ddev hostname some-project.ddev.site 127.0.0.1' on Windows if you use a Windows browser.
```
This suggestion will only work if ddev is also installed on the windows host.
So you have to install ddev on Windows and inside WSL to be able to ensure the basic functionallity is working, wihtout the need to manually editing files.

### Expected Behavior

I would expect ddev to work within WSL just as it does installed on a native operating system.
I don't expect to have to manually edit any files with an editor.
I don't expect to have to install and keep ddev up to date in Windows and WSL.

### Steps To Reproduce

1. Setup DDEV inside WSL according the documentation https://ddev.readthedocs.io/en/stable/
   - Skip "Windows (traditional/legacy)"
2. Run `ddev config` and `ddev start` in a new project inside WSL
3. Try to access the website through a browser installed on the host system

### Anything else?

This issue can be avoided by using the Windows binary inside WSL as proposed by the concept [DDEV Interop Based WSL Integration](https://gist.github.com/nico-loeber/6d6e8261827c5e4efa4ccf5b5cd04140), but @rfay had valid reasons for not implementing this concept as default.

This issue does affect the following issue of the DDEV Integration Plugin: https://github.com/php-perfect/ddev-intellij-plugin/issues/32

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

* #3818 - WSL2 users who
    * Don't use project_tld of *.ddev.site
    * Have a Fritzbox router or other situation with [DNS Rebinding disallowed ](https://ddev.readthedocs.io/en/latest/users/basics/troubleshooting/#dns-rebinding-prohibited) where *.ddev.site is not resolvable
    * Use additional_fqdns with non-*.ddev.site hostnames
    * And use their browser on the Windows side
have long had to manually edit the hosts file on the Windows side, or else just be confused by their browser's inability to look up some hostnames.

## TODO

- [x] Cache results of IsDDEVExeAvailable
- [x] Make usage tolerable if DDEV or gsudo is not installed on Windows side; test without
- [x] Consider using gsudo instead of sudo to execute.

## How this PR Solves The Problem:

Use ddev.exe (if it exists and is in the $PATH) on the Windows side as a proxy to edit the Windows hosts file.

## Manual Testing Instructions:

- [x] Install ddev.exe on Windows
- [x] `ddev config --additional-fqdns=one.example.com`
- [x] `ddev start`
- [x] Verify behavior if ddev.exe or sudo.exe doesn't exist in path (should behave traditionally in that case, editing the wsl2 /etc/hosts)
- [x] Verify escalation on Windows side, proper editing of Windows hosts file, and ability to look up `one.example.com` and ping it both on Windows and inside wsl2.

The hostname `one.example.com` should be added to the WIndows hosts file and should be resolvable by the browser either on Windows or in WSL2, and on the command line in WSL2 or Windows.

## Release/Deployment notes:

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4377"></a>

### CODE REVIEW

**Review by nico-loeber — CHANGES_REQUESTED** [review]
I did install the new binary on Windows and WSL.
Executing ddev hostname with and without sudo in WSL causes different error messages:

```
nl@XPS-9510-NL:~/projects/ddev-integration-demo$ ../../ddev hostname test.example.com 127.0.0.1
Unable to run ddev.exe hostname test.example.com 127.0.0.1 on Windows side, err=exit status 1, output=Could not write hosts file: open C:\WINDOWS\System32\drivers\etc\hosts: Access is denied.

Could not write hosts file: open /etc/hosts: permission denied
```

Without sudo my local user does not have the permission to edit the WSL hosts file. The windows ddev binary is found and can be executed by the wsl user, but it is lacking permission to edit the window hosts file.

```
nl@XPS-9510-NL:~/projects/ddev-integration-demo$ sudo ../../ddev hostname test.example.com 127.0.0.1
[sudo] password for nl:
WARN[0000] not reading global config file because running with root privileges
Not populating custom commands or hostadditions because running with root privileges
ddev.exe not found in $PATH, please install it on Windows side; err=exec: "ddev.exe": executable file not found in $PATH
 not found on windows side in $PATH, or can't run it: err=exec: no command, output=
Hostname 'test.example.com' added to hosts file
```

Executing ddev with sudo causes a warning for not reading the global config but editing the wsl hosts file works as expected. The domain is added to an already existing line in the hosts file which is a bit unexpted but I think this was already discussed in another issue.
The root user does not seem to have the windows binary in PATH. Probably the windows interopt functionality is not available for the root user environment.

I am not sure if gsudo would solve this issue, I haven't used it before.

I am not sure if using the windows binary as a proxy is ideal. You would need to maintain both binaries in sync regarding its version and stuff like that.

**Comment by rfay** [comment]
Thanks, yeah, on the regular windows setup ddev does a sudo, we just have to do it on the windows side. Thanks for testing that. I'm not sure why it was working on my machine.

**Comment by rfay** [comment]
Thanks so much for your review @nico-loeber - I apologize for testing on a machine that apparently had open permissions on the Windows hosts file. I have now tested on a clean Win11 machine.

* A specific version of DDEV is not required on the Windows side I don't believe, at least now. Probably a 4-year old version would work.
* sudo.exe is required and used now on the Windows side, as it always has been. It's installed with any standard Windows install of ddev.

**Comment by rfay** [comment]
I guess one option here would be to bundle sudo.exe and ddev.exe with a separate WSL2 package. Sounds hard.

However, if we were to convert the two WSL2 install scripts (which do install ddev.exe + sudo) into installers it would be a pretty friendly approach probably. 

I would love to have people running the Windows installer get a choice of traditional/docker-ce/docker-desktop installs and then have it do all that for them.

**Comment by alexbogias** [comment]
Looks like sudo.exe ddev.exe hostname also needs docker installed on windows side, or I am missing something?
I also have it installed inside WSL and I don't have any other issue except adding hostname in windows hosts

**Comment by rfay** [comment]
The scripted install installs Windows ddev (and gsudo) on the Windows side. That script is new in v1.21.4 though, perhaps docs improvement is required? https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows-wsl2

**Comment by rfay** [comment]
All you have to do is `choco install -y ddev` on the Windows side in an admin powershell.

**Comment by alexbogias** [comment]
I did! Looks like ddev command works but anyu other fails because no docker installed
image

**Comment by rfay** [comment]
Yeah, it's only installed so you can run `ddev hostname`, which does not require docker. That's how it can update the hosts file on the windows side. 

But ... you shouldn't need this to happen normally, unless you're using `additional_fqdns` or `project_tld`, if you're using `*.ddev.site`, the default, then ddev in wsl2 shouldn't be having to do this.

**Comment by alexbogias** [comment]
Please take a better look to the bottom of the screenshot. 
Yes, I need to work to a different project_tld. That's why it asks for docker?

**Comment by rfay** [comment]
I think you don't have the current v1.21.4 version of ddev on the Windows side. Could you please upgrade? `choco upgrade -y ddev`

**Comment by alexbogias** [comment]
image

**Comment by rfay** [comment]
It's possible I only tested on machines that had the docker client. You can fix this by just installing docker desktop and not having it start by default, `choco install -y docker` ( I think, not on windows right now).

But please open a new issue about that. 

Also, in your case you may want to turn on gsudo's credentials cache so it doesn't pester you all the time, https://github.com/gerardog/gsudo#credentials-cache

**Comment by rfay** [comment]
@alexbogias this should be fixed in 
* https://github.com/drud/ddev/pull/4553#issuecomment-1382154806

I'd sure love it if you could install those artifacts (both on Windows and on wsl2) and see if it solves this problem for you.

**Comment by alexbogias** [comment]
Thanks a lot for the fast fix mate

**Comment by alexbogias** [comment]
I will wait for the release and let you know

**Comment by alexbogias** [comment]
Still not adds it to windows hosts with sudo or not
image

**Comment by rfay** [comment]
Hi @alexbogias - this doesn't give me enough context to help you, but if you could please install DDEV v1.21.5-alpha1 on both linux and Windows that will help me. `choco install --pre ddev` on Windows and `apt upgrade ddev` on WSL2. Then please open an issue with the requested `ddev debug test` and explain exactly what happens. Thanks!

**Comment by alexbogias** [comment]
I installed ddev in host again but i dont want to install docker on windows just for the hosts

Anyway thanks for the help 
I leave here ddev debug test if you it helps.
```
PS C:\> ddev -v
time="2023-02-17T19:13:25+02:00" level=fatal msg="\x1b[31mUnable to get docker context: unable to run 'docker context inspect' - please make sure docker client is in path and up-to-date: exec: \"docker\": executable file not found in %PATH%\x1b[0m"

alex@abc: ~/Projects/example$ ddev -v
ddev version v1.21.5-alpha1

Running bash [-c /tmp/test_ddev.sh] 
======= Existing project config =========
These config files were loaded for project example: [/home/alex/Projects/example/.ddev/config.yaml]
name: example
type: wordpress
docroot: web
php_version: 7.4
webserver_type: nginx-fpm
webimage: drud/ddev-webserver:20230207_fix_nvm
router_http_port: 80
router_https_port: 443
additional_hostnames: [*.example]
additional_fqdns: []
database: {mysql 8.0}
upload_dir: app/uploads
mailhog_port: 8025
mailhog_https_port: 8026
phpmyadmin_port: 8036
phpmyadmin_https_port: 8037
project_tld: wdev
use_dns_when_possible: true
ngrok_args: --host-header=rewrite example.wdev:80
composer_version: 2
nodejs_version: 18
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-25716 in ../tryddevproject-25716 =========
OS Information: Linux unstablebox 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
User information: uid=1000(alex) gid=1000(alex) groups=1000(alex),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),33(www-data),44(video),46(plugdev),117(netdev),1001(docker)
DDEV version:  ITEM             VALUE                                   
 DDEV version     v1.21.5-alpha1
 architecture     amd64
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.4
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.4
 docker           23.0.1
 docker-compose   v2.15.1
 docker-platform  unstablebox
 mutagen          0.16.0
 os               linux
 router           drud/ddev-router:v1.21.4
 web              drud/ddev-webserver:20230207_fix_nvm
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
use-traefik=false
wsl2-no-windows-hosts-mgt=false

======= DOCKER info =========
docker location: -rwxr-xr-x 1 root root 35665448 Feb  9 21:46 /usr/bin/docker
docker version:
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:56 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:56 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
======= Docker Info =========
Docker platform: unstablebox 
Using docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.15.1
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 23.0.1
Able to run simple container that mounts a volume. 
Able to use internet inside container. 
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                 250.9G     84.5G    153.6G  35% /

Container ddev-example-db  Removed 
Container ddev-example-dba  Removed 
Container ddev-example-web  Removed 
Network ddev-example_default  Removed 
Project example has been stopped. 
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again. 
Existing docker containers: 
CONTAINER ID   IMAGE                         COMMAND                  CREATED        STATUS                    PORTS     NAMES
6c432de6d654   53411cc93c50                  "/bin/sh"                2 weeks ago    Created                             phpstorm_helpers_PS-223.8617.59
03ea6fef12ac   f817f3f2a48e                  "/bin/sh"                6 weeks ago    Created                             phpstorm_helpers_PS-223.8214.64
304898e5f1f9   drud/ddev-webserver:v1.21.4   "ls /mnt/ddev-global…"   2 months ago   Exited (0) 2 months ago             unruffled_bouman
b7dc3deccc2b   dd28bc5dcea2                  "/bin/sh"                2 months ago   Created                             phpstorm_helpers_PS-223.7571.212
Creating a new ddev project config in the current directory (/home/alex/Projects/tryddevproject-25716) 
Once completed, your configuration will be written to /home/alex/Projects/tryddevproject-25716/.ddev/config.yaml

Configuring unrecognized codebase as project type 'php' at /home/alex/Projects/tryddevproject-25716/web
Configuration complete. You may now run 'ddev start'. 
Network ddev_default created 
Starting tryddevproject-25716...
Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Network ddev-tryddevproject-25716_default  Created 
Container ddev-tryddevproject-25716-db  Started 
Container ddev-tryddevproject-25716-web  Started 
Container ddev-tryddevproject-25716-dba  Started 
Container ddev-router  Started 
Successfully started tryddevproject-25716 
Project can be reached at https://tryddevproject-25716.ddev.site https://127.0.0.1:32774
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 17 Feb 2023 17:11:01 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-25716.ddev.site from outside:
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Fri, 17 Feb 2023 17:11:02 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== full curl of http://tryddevproject-25716.ddev.site from outside:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-25716'
======== Project ownership on host:
drwxr-xr-x 4 alex alex 4096 Feb 17 19:10 ../tryddevproject-25716
======== Project ownership in container:
drwxr-xr-x 4 alex alex 4096 Feb 17 17:10 /var/www/html
======== In-container filesystem:
Filesystem     Type 1K-blocks     Used Available Use% Mounted on
/dev/sdc       ext4 263112772 88759308 160915308  36% /var/www/html
======== curl again of tryddevproject-25716 from host:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-25716'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds
If you're brave and you have jq you can delete all tryddevproject instances with this one-liner:
    ddev delete -Oy $(ddev list -j |jq -r .raw[].name | grep tryddevproject)
In the future ddev debug test will also provide this option.

Please delete this project after debugging with 'ddev delete -Oy tryddevproject-25716'
```

**Comment by rfay** [comment]
OK @alexbogias - There isn't any way for DDEV inside WSL2 to update the windows-side hosts file, which is where most people run their browser. That's why DDEV uses the Windows-side installation of DDEV (just a single binary, nothing else) to manage the hosts file there. If you're not willing to install as recommended, I can't really help you solve the problem. But you can...

* Not use non-ddev.site URLs (don't use additional_fqdns or project_tld)
* Run your browser inside WSL2

The scripts and info about installation are at https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows

**Comment by rfay** [comment]
You do *not* need Docker Desktop to install DDEV on the windows side. That was something that got fixed in DDEV v1.21.5-alpha1 and will be in upcoming v1.21.5.

**Comment by alexbogias** [comment]
Sorry but i still dont get it :(
image

**Comment by rfay** [comment]
Either that's a bug or the `ddev` you're running is not the one you installed with choco. Please check, `ddev --version` on the Windows side. `ddev --version` absolutely does not require the docker client. (I just checked and am able to run `ddev --version` and `ddev hostname` without any docker client installed with current DDEV).

**Comment by alexbogias** [comment]
Am really sorry @rfa! You are right! ddev --version works and I misstyped "hostname" before :(

**Pull request merged**
