### PR TITLE
[DOCS] Improvements and typo fixes

### PR DESCRIPTION
**Pull request by crydotsnake**

### CODE REVIEW

**Comment by crydotsnake** [comment]
Is there anything i have to change?.

**Comment by rfay** [comment]
Yes, this came in quite late and conflicts, so you'll need to rebase and fix the conflicts.

A lot of the changes you suggest are more your opinion than definite needs, so I'll take another look at it in the v1.16 process.

I've been ignoring v1.16-targeted PRs until v1.15 is fully sorted out, so that's why I haven't done anything here.

**Comment by rfay** [comment]
I rebased this and reviewed it, made a number of trivial changes. PhpStorm really is PhpStorm, please ask before deciding usage in the future.

**Comment by rfay** [comment]
I pushed the results in here.

**Comment by crydotsnake** [comment]
Okay. Thanks a lot Randy!. And sorry!. Next time, i will make the PR better.

**Pull request merged**
