### PR TITLE
[docs] apt-key is deprecated

### PR DESCRIPTION
**Pull request by mhuber84**
## The Problem/Issue/Bug:
apt-key is deprecated

## How this PR Solves The Problem:
Update documentation with suggestion from https://itsfoss.com/apt-key-deprecated/

### CODE REVIEW

**Comment by rfay** [comment]
Hmm, I thought this was already fixed everywhere with 
* https://github.com/drud/ddev/pull/4324

**Comment by mhuber84** [comment]
Sorry, my fault. I haven't noticed that the text here in the repository already doesn't use apt-key anymore. On https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/ are the old instructions. So my pull request is not needed anymore because of the apt-key deprecation.
But https://itsfoss.com/apt-key-deprecated/ says, that there are two ways to import the GPG keys and this way is the proper way. But I don't know if this is really important. In my tests both ways work.

**Comment by rfay** [comment]
Hmm, https://itsfoss.com/apt-key-deprecated/ puts does what the DDEV docs already do, so I'm confused. 

Anyway, we'll close this and please do report if you have any issues with the current recommendation.

Thanks for taking the time to help sort it out! Your docs improvements and other contributions are always welcome.

**Comment by mhuber84** [comment]
> The article you quote says the keys belong in /etc/apt/trusted.gpg.d but for some reason you're changing that.

"Solution 2: Adding the GPG keys to the system to the proper way" says /usr/share/keyrings/. But it doesn't explain why and I'm not that experienced in the linux directory structures.

**Comment by rfay** [comment]
Yet everywhere in the article they use /etc/apt/trusted.gpg.d :( I think it's just a confusing article. 

A quick look around the internet shows it being done into both of these directories. I guess we'll live and learn.

**Comment by FoxtrotCZ** [comment]
Just wanna say, Docker uses etc/apt/keyrings
https://docs.docker.com/engine/install/ubuntu/
Could be good idea to use the same location.

**Comment by rfay** [comment]
If you have something more authoritative than just what docker does, I'm sure open to it. 

The error message says 
> Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).

It looks to me like Ubuntu (and probably Debian) say 

> Note: Instead of using this command a keyring should be placed directly in the
           [/etc/apt/trusted.gpg.d/](file:///etc/apt/trusted.gpg.d/) directory with a descriptive name and either "gpg" or "asc" as
           file extension.

https://manpages.ubuntu.com/manpages/jammy/man8/apt-key.8.html

**Pull request closed without merging**
