### PR TITLE
Apache for ddev, fixes #628

### LINKED ISSUE #628: [Feature-Request] Support Apache in addition to Nginx
It would be nice to have the possibility to choose between Apache/Nginx on project setup.

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

Lots of users want Apache, see OP #628, mostly for htaccess types of situations.

We expect this to be an "experimental support" situation; full tests may not be in place when we release, and we can then learn from people's experience.

## How this PR Solves The Problem:

Provides the ability to configure the webserver type in .ddev/config.yaml, you can use 

```
webserver_type: apache-fpm
webserver_type: apache-cgi
webserver_type: nginx-fpm (the default)
```

TODO:
- [x] Custom configuration for apache (I expect we'll spin this off into some other issue)
- [x] mod_rewrite (for drupal rewrites) doesn't seem to be working yet.
- [x] ddev logs isn't showing the right stuff for apache
- [x] docroot needs to be substituted/updated in apache config.
- [x] apache-cgi not yet working
- [ ] Tests of course. Complete tests for all permutations will have to be deferred to improvements of circle tests and parallelization
- [ ] Spin off issue for full testing of all apache2 permutations (parallel!)
- [x] Docs (config override, etc.)

This PR is currently in the "take it for a spin and report your results but don't take it too seriously" state. 

I think we might be able to enable this as "experimental" in the v1.2.0 release.

## Manual Testing Instructions:

* Make sure you have the latest ddev-webserver with `docker pull drud/ddev-webserver:20180815_apache`
* `ddev config` and edit your .ddev/config.yaml to use the webserver_type you prefer.
`ddev start`
* Experiment. On Drupal, you can visit admin/reports/status to see the webserver, etc.
* Note that as of 2018-08-08, this doesn't work with a docroot outside the project root yet.

## Automated Testing Overview:

This has no tests yet.

## Related Issue Link(s):

OP #628

### CODE REVIEW

**Comment by rfay** [comment]
If you do a pull as suggested in the instructions you'll see mod_rewrite working now

**Comment by rickmanelius** [comment]
@rfay Confirmed that mod_rewrite works with the latest docker image!

**Comment by rfay** [comment]
This is now ready for first review, everything I know of is working fine in apache-fpm and apache-cgi. I'd appreciate reviews here, and I'll also ask for reviews from the TYPO3 folks.

**Comment by rfay** [comment]
We'd love to have people try this out, especially people who love Apache. You can get the builds from https://circleci.com/gh/drud/ddev/3272#artifacts/containers/0 - All you have to do is `ddev config` your project and then set the `webserver_type: apache-fpm` or `webserver_type: apache-cgi` in your config.yaml, then `ddev start`. Please report your results and issues.

**Comment by rndmh3ro** [comment]
I tested both apache-fpm and apache-cgi with a boilerplate TYPO3 setup.

**I did not find anything that didn't work**. The installtool said everything was fine, no errors in any logs, htaccess works...

Here's my config:
```
APIVersion: v1.1.1-21-gb5797920
name: typo3-boilerplate
type: typo3
docroot: web
php_version: "7.1"
webserver_type: apache-cgi
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: true
additional_hostnames: []
additional_fqdns: []
provider: default
hooks:
  post-start:
  - exec: composer install -d /var/www/html
  - exec: sudo apt-get -qq update
  - exec: sudo apt-get -qq install --no-install-recommends --no-install-suggests -y   ack-grep
      make graphicsmagick imagemagick graphviz pngquant curl unzip htop catdoc poppler-utils
      build-essential git subversion unzip unrtf software-properties-common libsqlite3-dev
  - exec: npm install
  - exec: ../node_modules/gulp/bin/gulp.js frontend
  - exec: ../node_modules/gulp/bin/gulp.js js-lint
  - exec: ../node_modules/gulp/bin/gulp.js php
  - exec: vendor/bin/typo3cms cache:flush
  - exec: vendor/bin/typo3cms database:updateschema
  - exec: vendor/bin/typo3cms cache:runcacheboostqueue
  - exec: vendor/bin/typo3cms language:update
  - exec: vendor/bin/typo3cms install:fixfolderstructure
```


Good work!

**Comment by rfay** [comment]
Thanks so much for your review @rndmh3ro ! So glad it worked for you.

**Comment by rfay** [comment]
The code provides the capability to do CMS-specific configurations (and also config overrides) but we don't know of any yet, so I didn't do any.

**Comment by rickmanelius** [comment]
Cool. That's why I didn't tag as "request changes" because I figured I might be missing some context and you're correct that given this is experimental, we can wait for people to respond before worrying about it. I'm curious just how many users actually end up using Apache... so we'll see!

**Comment by rfay** [comment]
Thanks for the review @andrewfrench - I agree that the env var override of default webserver type is hokey, just was hoping for a quick path to get some testing.

I think the path forward to inclusion in the next release could be:

1. Debug the failing tests under apache-fpm/apache-cgi and get them working so this passes or
2. Remove the fpm and cgi stanzas and just pull (and spin off testing issue) and include in v1.2.0

Of course I'd be happier with the first option. But it may not be possible. Anyway, this is yours to drive home, and thanks.

**Comment by andrewfrench** [comment]
Digging into these test failures now: I'm able to recreate the issue outside of a full test suite by repeatedly `ddev restart`ing a project with the `apache-cgi` server type. I haven't nailed down how many cycles it'll take to get there, but it will consistently happen with enough restarts.

**Comment by rfay** [comment]
Thanks for the hint on how to break it @andrewfrench 
`while true; do let i=i+1; echo $i; ddev rm; ddev start || break; done`
`while true; do let i=i+1; echo $i; ddev restart || break; done`

When it breaks (so far on the restart path only) apache has died in the container. This actually is probably an apache or docker flaw.

**Pull request merged**
