### PR TITLE
Be explicit about use of sudo - tell them what we're going to do

### PR DESCRIPTION
**Pull request by rfay**
## The Problem:

We were using sudo to get full root privileges without expressly saying what we were doing (and without controlling the path of what we were executing), see https://github.com/drud/ddev/issues/117

## The Fix:

* Say exactly what we're going to do
* Use the fullpath of the running executable (golang 1.8.1 os.Executable())
* Update circle.yml to install golang 1.8.1 (used in tests). Ooops. 

This does *not* stop and ask permission, which it probably could do.

## The Test:

* Manually remove current sitename from /etc/hosts
* Use `ddev start` to see the results

## Related Issue Link(s):

[Security: ddev can be used to sudo an arbitrary command](https://github.com/drud/ddev/issues/117)

### CODE REVIEW

**Comment by rfay** [comment]
Besides normal review, this needs a run-through "Needs decision" from @rickmanelius to make sure he's OK with the UI.

**Comment by rfay** [comment]
Thanks, rebased and addressed those nits.

**Comment by rfay** [comment]
@rickmanelius here's the quick view of what the UI is at this point. If you like it as is this goes in.

http://screencast-o-matic.com/watch/cbfTbpXIBG

**Comment by rickmanelius** [comment]
@beeradb Tanner and I have given the 👍  on this one. Looking for your merge :)

**Comment by beeradb** [comment]
We had discussed (re)introducing a `util.Warning()` and using it for this. Have we decided not to?

I'm OK w/ this as-is if we're not in favor of warning text at this juncture.

**Comment by rfay** [comment]
I was thinking based on @rickmanelius's comment that the util.Warning() was the answer. I was going to go get it.

**Comment by rfay** [comment]
Hopefull final version: 
6__default__python__and_5__default__bash_

**Pull request merged**
