### PR TITLE
Bumped spellcheck GitHub action to version 0.20.0

### PR DESCRIPTION
**Pull request by jonasbn**
I have recently released 0.20.0 of the spellcheck GitHub action, I can see that you are using 0.8.0, so an update could be useful to you. Let me know if you have any issues with the proposal and I will try to accommodate.

I can recommend [Dependabot](https://github.com/dependabot) for keeping your GitHub actions up to date, if you want a PR proposing a basic configuration, please let me know.

## Release/Deployment notes:

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3466"></a>

### CODE REVIEW

**Comment by rfay** [comment]
Thanks! A PR with config that uses dependabot would be fine. Mostly dependabot has just been a nuisance, but for this I'd think it might be OK.

**Review by rfay — APPROVED** [review]
Thanks!

**Comment by jonasbn** [comment]
Hi @rfay 

I have created PR #3473 with a proposal for a basic Dependabot configuration for GitHub Actions solely and for your review/evaluation

**Comment by rfay** [comment]
Thanks!

**Pull request merged**
