### PR TITLE
adds support for https in ddev router

### PR DESCRIPTION
**Pull request by tannerjfco**
## The Problem/Issue/Bug:
#232 OP - We want to support both HTTP and HTTPS for local dev without redirect.

## How this PR Solves The Problem:
- Updates to use provisional ssl tag for ddev-router, introducing https support w/ self-signed certs
- Updates site docker-compose.yml template to define new HTTPS_EXPOSE
- Updates router setup to ensure ports defined in HTTPS_EXPOSE are exposed on ddev-router.
- Updates successful start message to include both HTTP and HTTPS URL options (I'm not sure if this is what we want or if we want to do something different)

## Manual Testing Instructions:
This can be tested by building a binary from this PR and spinning up a test ddev site. You'll want to ensure you get a freshly-generated docker-compose for the site. The site should spin up successfully, and you should be able to access the site at both HTTP and HTTPS

### CODE REVIEW

**Comment by tannerjfco** [comment]
How we communicate all of this is something we definitely need to improve. I think its worth displaying port usage, especially if the port has been customized to be different from 80 or 443. What if we displayed the port in the URLs in start message and describe, on condition of non-standard port?

**Comment by rfay** [comment]
I was actually talking about the bound host ports for accessing http and https. As you've pointed out before, people could actually use those directly and we should consider exposing the URL/port they would use that way; it would even give us a way to bail on bringing up the web container.

On this site:
```
            "Ports": {
                "443/tcp": null,
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32839"
                    }
                ],
                "8025/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32838"
                    }
                ]
```
Of course I can hit the website at http://localhost:32839/ as well as http://randyfay.ddev.local/ - allowing them the option of knowing about/using the host port with localhost gives them a workaround for both hostname resolution *and* for port 80 cleanup.

**Comment by rickmanelius** [comment]
I'm planning on reviewing this tomorrow (Thursday). Sorry for not getting to it sooner.

**Comment by tannerjfco** [comment]
@rickmanelius The error message from your d7 test is from the web container, not ddev-router. I encountered it as well, and in my case it was due to a settings.php present from previous use pointing to an empty db. Once I resolved this, the site worked as expected for me.

**Comment by tannerjfco** [comment]
> Right now, the tag here is not the same as the tip of docker.ddev-router, so not a very good test.

I have built/pushed v0.4.3-8-g178232f for router and updated to that in makefile

> Currently, ddev-router is mounting the whole of ~/.ddev

This has been updated to mount ~/.ddev/certs instead

> Forcing the $base_url usually confuses drupal. So maybe we can just stop doing it?

I'm pretty sure we can remove this, and I've done so. I think this was done to force the URL to be correct for things like `drush uli`, however this approach isn't valid for D8 as base_url was removed. We've since implemented a drushrc.php file to address this concern.

I also took some more time to play with sites in HTTPS, and just kept hitting mixed mode brokenness on sites. This is because we weren't setting `$_SERVER['HTTPS'] = 'on';` so that PHP applications know to serve over HTTPS. I've introduced drud/docker.nginx-php-fpm-local#40 to address this issue in a way that should allow most PHP apps to serve over HTTPS correctly.

**Comment by tannerjfco** [comment]
I have updated this to conditionally display the HTTPS versions of the URL at start and in list/describe. We still have the problem of how users will update to get HTTPS on existing sites/configs, as they will need an updated web image tag and the HTTPS_EXPOSE var set in the site docker-compose.yml. However, these are issues that extend beyond the concerns of this particular feature. I think #343 could help with some of this, but either way we'll need to figure out a path forward.

**Comment by rickmanelius** [comment]
Next review in progress (will re-update and edit this comment with final testing and recommendations).

## Reference

* PR https://github.com/drud/ddev/pull/522
* OP https://github.com/drud/ddev/issues/232

## Preparation

* `brew uninstall ddev` (removes latest release binary)
* `git fetch --all`
* `git checkout tannerjfco/router-https-support`
* `make clean && make darwin`
* `ddev version` outputs v0.9.3-19-g5e80b698 (matches hash of tannerjfco/router-https-support)
* Shut down and remove all ddev sites (i.e. `ddev rm --remove-data`)
* `ddev list` shows no running applications and `docker ps` shows no active containers.

## Repositories Used

* [WordPress Latest - 4.9.0](https://wordpress.org/latest.zip)
* [Drupal 7 Latest 7.56](https://www.drupal.org/project/drupal/releases/7.56)

**Comment by rickmanelius** [comment]
@beeradb I know you had some open questions on upgrade path which I know is valid but probably best scoped to another issue where we discuss who maintains and manages the settings files, the docker compose files, the config.yml, etc because those are 100% valid concerns but not entirely attached to the scope of this specific ticket and something we will likely need to better address with all future updates.

**Pull request merged**
