### PR TITLE
Improve detection of  `craftcms` project type even when not in project root, fixes #4329

### LINKED ISSUE #4329: File operations in `craftCmsPostStartAction` are not performed when Craft CMS is installed in a subdirectory
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

_No response_

### Expected Behavior

When first starting a project with `--project-type=craftcms` after Craft CMS has been installed via `ddev composer create -y --no-scripts --no-install craftcms/craft`, the expectation is that the `.env.example.dev` file is copied and programmatically filled out with `ddev` aware configuration values. Additionally, `composer.json.default` is supposed to be renamed to `composer.json`.

### Actual Behavior

A Craft CMS project is installed, but without a copied and preconfigured `.env` file. `composer.json.default` is not renamed to `composer.json`. This then leads to a failure of the Craft installation script as there is no `.env` file and therefore no database configuration.

### Steps To Reproduce

**Set up a Craft CMS project and specify a subdirectory as the installation location:**
`ddev config --project-type=craftcms --docroot=app/web --create-docroot --composer-root=app --web-environment-add=CRAFT_CMD_ROOT=./app`

**Install Craft:**
`ddev composer create -y --no-scripts --no-install craftcms/craft`

`cd app`

Note the absence of an `.env` file.

### Anything else?

This is most likely due to the way that `craftCmsPostStartAction` is looking for files, e.g.:

`app.AppRoot` may not be the most reliable way to verify a Craft install or to check for the existence of the `.env` or `.env.example.dev` files, since once the Craft installation is in a subdirectory, it's outside `app.AppRoot` as far as DDEV is concerned. Maybe using `app.composerRoot` would be more reliable for these operations, since that is actually where `ddev composer create` puts Craft.

### PR DESCRIPTION
**Pull request by flynnt**
## The Problem/Issue/Bug:
For projects of type `craftcms`, file and other operations in `craftCmsPostStartAction()` are not performed when Craft CMS is installed in a subdirectory, which leads to Craft installation failures.

## How this PR Solves The Problem:
This PR changes the location that is queried for the `craft` executable in `isCraftCmsApp()` from `app.AppRoot` to `app.ComposerRoot`. This is probably a more reliable way to test whether or not a project is a Craft project, since the Composer root is where Craft will ultimately reside. For projects that don't install Craft in a subdirectory, this will usually be the same as `app.AppRoot`. Projects that do install Craft in a subdirectory will also have to manually configure the Composer root in order for `ddev composer` to work. In either case, DDEV maintains an awareness of where Craft is.

This PR also updates where the methods in `craftCmsPostStartAction()` look for `.env` and `composer.json` files to `app.ComposerRoot`, because the logic regarding the most reliable place to look for Craft assets above applies in these cases as well.

## Manual Testing Instructions:
**Basic Install:**
`mkdir my-craft-project`
`cd my-craft-project`
`ddev config --project-type=craftcms --docroot=web --create-docroot`
`ddev composer create -y --no-scripts --no-install craftcms/craft`
`ddev start`
`ddev composer update`
`ddev craft install`
`ddev launch`

**Subdirectory Installation:**
`mkdir my-craft-project`
`cd my-craft-project`
`ddev config --project-type=craftcms --docroot=app/web --create-docroot --composer-root=app --web-environment-add=CRAFT_CMD_ROOT=./app`
`ddev composer create -y --no-scripts --no-install craftcms/craft`
`ddev start`
`ddev composer update`
`ddev craft install`
`ddev launch`

## Related Issue Link(s):
https://github.com/drud/ddev/issues/4329

## Release/Deployment notes:

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4331"></a>

### CODE REVIEW

**Comment by rfay** [comment]
Ping me in here when you push new commits so I can re-run tests - as first-time contributor (thanks!) I have to start the tests when you add commits.

**Comment by flynnt** [comment]
> Ping me in here when you push new commits so I can re-run tests - as first-time contributor (thanks!) I have to start the tests when you add commits.

Oh, ok, thanks. I think I might have a failing test in `apptypes_test.go` related to the fact that if `app.ComposerRoot` isn't explicitly defined it just returns an empty string. I will try to fix that once I get Gitpod going.

**Comment by flynnt** [comment]
@rfay I have some new commits to test out. This should get the build passing. I mean, `apptypes_test.go` was passing in Gitpod anyway.

**Comment by rfay** [comment]
@flynnt if this is ready for review, then change it from draft to ready for review, thanks.

**Comment by flynnt** [comment]
@rfay I still need to manually test this with the build artifacts. I am traveling tomorrow, so probably won't get to it until the evening, or Thursday.

**Comment by rfay** [comment]
That's great, thanks so much. And thanks for manually testing!

**Comment by flynnt** [comment]
@rfay I did some manual testing, and there's still a small issue. [This line](https://github.com/drud/ddev/pull/4331/files#diff-5799e15d18a89a9d31d37f6e9e80b06f41c6e5e20bcfc74ebeb8af8f10d06d3bL146) calls `os.Create` without considering the Craft installation location, so while the initial copy of the `.env` file works in a subdirectory, the modified `.env` ultimately gets written out to `app.AppRoot`, so you actually end up with two `.env` files. I think I know how to fix it, but it's hard for me to test changes as I'm making them. Is there a way to run builds in Gitpod so that the `ddev` executable in there reflects changes to the source files?

**Comment by rfay** [comment]
Sure. If you are using a gitpod build with the URL of this PR, https://gitpod.io/#https://github.com/drud/ddev/pull/4331

then all you have to do is `make` and you'll immediately have the new binary. Use `ddev --version` and `which ddev` to verify.

**Comment by flynnt** [comment]
> Sure. If you are using a gitpod build with the URL of this PR, https://gitpod.io/#https://github.com/drud/ddev/pull/4331
> 
> then all you have to do is `make` and you'll immediately have the new binary. Use `ddev --version` and `which ddev` to verify.

Amazing. Ok, I think this one is ready for review. Updating.

**Review by rfay — CHANGES_REQUESTED** [review]
You're awesome for taking this on! I know how hard it can be to work in an unfamiliar environment.

I made a few suggestions, but once you see the pattern you'll want to look at everything here.

Happy to help, and thanks for taking this on!

**Comment by flynnt** [comment]
@rfay Ok, I manually tested everything with those changes, and it all appears to be working. It's pretty nice that `filePath.join()` discards segments that don't exist.

**Review by rfay — APPROVED** [review]
Thanks for all your work on this. I reviewed the code again and manually tested both paths and everything seems fine.

**Pull request merged**
