### PR TITLE
Use alpine-based mariadb container

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

This PR integrates a new alpine-based mariadb 10.1 container. It passes tests and works on Windows.

## Manual Testing Instructions:

Use regular ddev commands in many situations, on many OSs. 
Try `ddev rm` with and without -R and verify appropriate behavior.

## Related Issue Link(s):

OP: https://github.com/drud/ddev/issues/488
docker.mysql-local PR to incorporate this: https://github.com/drud/docker.mysql-local/pull/38
Earlier ddev PR explaining all the problems with debian-based mariadb: https://github.com/drud/ddev/pull/572
Earlier debian-based mariadb container attempt: https://github.com/drud/docker.mysql-local/pull/30

### CODE REVIEW

**Comment by rfay** [comment]
I'll reopen this when I need it.

**Comment by cweagans** [comment]
Honestly, I'm not entirely comfortable with putting maria in ddev after my previous attempt without knowing specifically what caused maria to fail. I'll dig into the differences in packaging if that would help, but maybe some more understanding here would be a good idea.

**Comment by rfay** [comment]
@cweagans I'd rather go forward with this sooner than later, as we get some miles on it before the next release. If we delay too long we won't have enough experience with it ourselves. So hoping for your approval.

**Comment by cweagans** [comment]
Alpine build args are here: https://git.alpinelinux.org/cgit/aports/tree/main/mariadb/APKBUILD?h=3.7-stable#n60

I'm having a hard time finding the Debian ones though. Any pointers on where that stuff might live? I'm not super familiar with building Debian packages, but basically, I'm just looking for the equivalent to the Alpine link above specifically for however the mariadb-server package is built.

**Comment by rfay** [comment]
I'm afraid I'm not much help. But also pretty sure that mysql-server in a debian container on windows may have the same result. 

An interesting factoid: In Debian Stretch, mariadb is the default mysql implementation. https://www.debian.org/releases/stretch/s390/release-notes/ch-whats-new.en.html#mariadb-replaces-mysql - However, in my experiments I was using the packages provided on the mariadb page, as I think you were.

[Generic mariadb build instructions](https://mariadb.com/kb/en/library/generic-build-instructions/)

[Main team entry point](https://wiki.debian.org/Teams/MySQL/MariaDB)

I think a mirror of the built-in debian build is at https://github.com/ottok/mariadb-10.1

Oh, interesting, I see on https://mariadb.com/kb/en/library/mariadb-10130-release-notes/ "A file format compatibility bug that was introduced in MariaDB 10.1.0 was fixed in MariaDB 10.1.21.", but I would have been using 10.1.30 I'm pretty sure.

**Pull request merged**
