### PR TITLE
[output] improve custom config output in config.go

### PR DESCRIPTION
**Pull request by rpkoller**
## The Problem/Issue/Bug:
PR for #4182

Before:
Screen Shot 2022-09-10 at 01 44 19

After: 
Screen Shot 2022-09-10 at 01 25 45

## Release/Deployment notes:

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4202"></a>

### CODE REVIEW

**Comment by rfay** [comment]
Let me know when you've manually tested this and you like it, thanks.

**Comment by rpkoller** [comment]
This issue was done via the CLI. Therefore I had already manually tested it since it was one of the recommended steps before the PR within the docs - see the after screenshot in the issue summary. For me as as none native speaker it looks ok  - one long sentence got cut into two and the term usually got removed. the final say i would leave more to a native speaker ;)  

on a side note. i wonder what changed with the PR now? when i've submitted it i had 3 or 4 failing tests also after a rerun. and without changing anything the tests seem good to go now?

**Comment by rfay** [comment]
Yeah, you need to test it from the PR please.

Test fail regularly due to various issues with Docker Desktop and Colima. So I usually pay attention and solve the problems and restart.

**Comment by rpkoller** [comment]
Screen Shot 2022-09-14 at 23 11 32
the output remained the same to the one from the issue summary. no visible changes.

**Review by rfay — APPROVED** [review]
Thanks!

**Pull request merged**
