### PR TITLE
Adds import-db and import-files commands

### PR DESCRIPTION
**Pull request by tannerjfco**
## The Problem:
See #33 for full details. Our existing import functionality is heavily reliant on site archives in a very specific structure and naming convention. We want import functionality that does not require rigid archive formats, and we want to be able to separately import the database and files as desired.
## The Fix:
This PR introduces 2 new commands, `ddev import-db` and `ddev import-files`. The commands have some similar functionality. They both accept a path provided by user prompt or by using a `--src` flag. They both accept `tar.gz` archives, and if provided, will be extracted so the assets within can be imported.

The import-db command ultimately expects a single `.sql` file be provided. This means either a file path should be provided directly, or an archive containing a sql dump at the root of the archive should be provided.

The import-files command ultimately expects a directory path be provided. The provided directory's contents will be copied to the default uploaded files directory for the given application. In Drupal's case, this is `sites/default/files`. In WordPress' case, this is `wp-content/uploads`. If an archive is provided, the contents of the archive are copied as-is to the default location.

This also implements a new wp-config.php template that will work with a standard installation. Full details of this can be seen at the closed PR for this task #112 

This PR *does not* remove the previous import command and its related functionality. For the purpose of easier reviews, the removal will be completed in a separate PR.

## The Test:
**Note**: You will need to set the database container tag in the `.ddev/config.yaml` of the site you are testing to the `import-update` tag.

You should be able to test this with a pre-existing site, provided the site uses standard location for uploaded files. You can also use the following test sites that I have compiled test assets for:
https://github.com/drud/drupal8/releases/tag/v0.2.2
https://github.com/drud/wordpress/releases/tag/v0.1.0
https://github.com/drud/drupal-kickstart/releases/tag/v0.1.0

### Usage examples:
examples are for import-files, but also valid for import-db, provided you are providing a sql dump.
Prompt:
```
ddev import-files
Provide the path to the directory or archive you wish to import. Please note, if the destination directory exists, it will be replaced with the import assets specified here.
Import path:
~/Desktop/wp-files.tar.gz
Successfully imported files for testsite1
```
Flag:
```
ddev import-files --src ~/Desktop/wp-files.tar.gz
```
or
```
ddev import-files --src=~/Desktop/wp-files.tar.gz
```

## Automation Overview:
I have added test coverage for ImportDB and ImportFiles at the local plugin level. I have also added test coverage for the new appimport and files packages.

## Related Issue Link(s):
#33 OP
#107 / #112  update wp-config template
drud/mysql-docker-local#11 - mysql import updates

## Release/Deployment notes:
Does this affect anything else, or are there ramifications for other code? Does anything have to be done on deployment?

This PR *does not* remove the previous import command and its related functionality. For the purpose of easier reviews, the removal will be completed in a separate PR.

drud/mysql-docker-local#11 - mysql import updates is required for this change. A new tag will need to be pushed for this container.

### CODE REVIEW

**Comment by rickmanelius** [comment]
Looks like there are some remaining clean-up items. FWIW, I would prefer that the imports work with both tar and tar zips, given that users will likely attempt from both (even though I would bet zips are more popular for files and databases are more likely to be unzipped). If we need to split the remaining file extention/zip support to another ticket, I'm cool with that because there is a lot of work here that should get merged sooner than later!

**Comment by rfay** [comment]
@rickmanelius I assume you're saying .tar and .tar.gz - or are you also saying file imports using .zip ? .zip was spun off into https://github.com/drud/ddev/issues/147

IMO if you think .tar is important (probably is) we should spin that off into another issue, as this one is way overdue for pull.

**Comment by tannerjfco** [comment]
With the latest updates, sql.gz import should work as expected. Additionally, tar files will work whether or not they are gzipped. Once we have green board on the tests, this should be ready to come in.

**Comment by rfay** [comment]
I tested .sql, .sql.gz for database and .tar, .tar.gz, .tgz for files. They all seemed to work fine. Approved. There will be followups, we know. Huge accomplishment, thanks for hanging in there.

**Pull request merged**
