### PR TITLE
Massive docs rewrite and reorg and TABS

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

The DDEV doc have grown organically over a really long time, and haven't had a reorg in forever. And lots of places

## How this PR Solves The Problem:

Massive rework of docs. Introduce tabs and warning and notes where the going was rough. New theme details from material-mkdocs.

## TODO

- [x] We're using the insider version of mkdocs-material - make sure the build uses that. 
- [x] Fix links and other things in main README.
- [x] Experiment with moving things below tabs into separate files
- [x] Improve the developer docs so people know better how to install
- [x] Include developer docs
- [x] Edit code that refers to ddev.readthedocs.io
- [ ] After pulling this, refresh the Gitpod Docker image.
- [x] Fix the background of annotations (same as rest)
- [x] Make sure there's not lost content underneath the header

## Manual Testing Instructions:

Read the docs at https://test-ddev.readthedocs.io/en/latest/

## Release/Deployment notes:

- [ ] After merge, push up the Gitpod.io Docker image. Can't be done before that.

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3944"></a>

### CODE REVIEW

**Comment by mikebarkas** [comment]
Reviewed the docs at https://test-ddev.readthedocs.io/en/latest/

I feel the tab navigation across the top makes navigating easier and the user experience is better.
Search works well
Light/dark mode works well
The tabs for the different os:arch is a nice addition

The font size in the admonition notes is a little small (maybe because of my age 🤪 )
`.md-typeset :is(.admonition,details) { font-size: .64rem;} `
.64rem brings it down to about 12px for me

----

admonition-font-size

**Comment by rfay** [comment]
Thanks @mikebarkas - One of the things that I note is a lack of separation between the tabbed sections and the content that follows (under all tabs). Ideas on how to sort that?

**Comment by CollierCZ** [comment]
> a lack of separation between the tabbed sections and the content that follows (under all tabs)

I'm not sure I understand this. Could you explain it or use a screenshot?

**Comment by rfay** [comment]
Thanks @CollierCZ - This one shows it... there's no separation between the end of the tabbed topic and the next thing.

image

**Comment by CollierCZ** [comment]
Ah, yes. Was looking at the top navigation for some reason.

We have the same issue in the Platform.sh docs ([example](https://docs.platform.sh/administration/organizations.html#manage-your-organization-users)). For now, we are learning to live with it. But we plan to get a designer to think about the problem before too very long.

**Comment by rfay** [comment]
If anybody wants to experiment with this a bit, https://ddev.readthedocs.io/en/latest/developers/testing-docs/ has how to run mkdocs locally. It's easy. 

* `content/assets/*` can be enabled in mkdocs.yml, I have currently turned off the old ones.
* You can fiddle with the `palette` in the theme in mkdocs.yml
* See [mkdocs-material](https://github.com/squidfunk/mkdocs-material) and [mkdocs-material docs](https://squidfunk.github.io/mkdocs-material/getting-started/)

**Comment by tyler36** [comment]
It looks really nice.

My only feedback would be to increase paragraph spacing and line height. The documentation is comprehensive but the blocks are quite dense.

**Comment by rfay** [comment]
@mikebarkas per https://github.com/drud/ddev/pull/3944#issuecomment-1168645395 I increased the admonition font size a bit, please take a look. We can do anything we want in the extra.css. An example is the admonition in https://test-ddev.readthedocs.io/en/latest/users/install/performance/#enabling-mutagen

**Comment by tyler36** [comment]
Great work!

**Pull request merged**
