### PR TITLE
[docs] Implement temporarily fix for nested tab navigation

### PR DESCRIPTION
**Pull request by mikesnoeren**
## The Problem/Issue/Bug:
There is currently an issue where tabs don't automatically open when an anchor link within them is visited.
Related issues/ PRs:
- https://github.com/drud/ddev/issues/4019
- https://github.com/drud/ddev/pull/4009

## How this PR Solves The Problem:
I've written a script that opens the tab that our hash heading is within and then scroll our viewport to that heading. 
If the tabs are nested within eachother this script will also open the outer tab. 
**Keep in mind:** If there's a third level of tabs this script will not work. Tabs should be nested more than once to maintain readability!

## Manual Testing Instructions:
You can view this PR's results by using [this link](https://ddev--4046.org.readthedocs.build/en/4046/users/install/performance/#using-nfs-to-mount-the-project-into-the-web-container).

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4046"></a>

### CODE REVIEW

**Comment by rfay** [comment]
Thanks for this! 

It's hard to fully test because the behavior of nav has changed, and not much is showing on the left side.

Here's https://ddev.readthedocs.io/en/latest/users/install/docker-installation/:


Docker_Installation_-_DDEV_Docs


And here's your PR: https://ddev--4046.org.readthedocs.build/en/4046/users/install/docker-installation/

Docker_Installation_-_DDEV_Docs


What's up with that? 

I did find a tab to test with in https://ddev--4046.org.readthedocs.build/en/4046/users/install/performance/ and it kind-of-works pretty nicely there, so I'm sure this PR has great potential.

**Comment by mikesnoeren** [comment]
> What's up with that?

Oops! Forgot to sync up with remote again, I fixed it and everything is up-to-date now!
Could you please review again: https://ddev--4046.org.readthedocs.build/en/4046/users/install/docker-installation/

**Comment by mikesnoeren** [comment]
One thing I noticed that unfortunately isn't fixed by this PR is the highlighting bug in the menu, which is supposed to be a indicator showing the user how far they have scrolled..

This strange behaviour is caused by the heading placement being in tabs which messes with the javascript detecting if we've scrolled past it..

**Comment by rfay** [comment]
It's quite massively better, and a great step forward IMO. 

There are still problems that I don't know you could sort out with this technique, but I'd love you to try. 

If you search for "Ubuntu" and choose WSL2, you'll get https://ddev--4046.org.readthedocs.build/en/4046/users/install/ddev-installation/#windows-wsl2 - but it doesn't have the right tab open.

**Comment by rfay** [comment]
Seems to me like you're going to be totally successful on this, it will be a great addition for v1.20.0, and may prevent us from having to rip out tabs.

**Comment by mikesnoeren** [comment]
> If you search for "Ubuntu" and choose WSL2, you'll get https://ddev--4046.org.readthedocs.build/en/4046/users/install/ddev-installation/#windows-wsl2 - but it doesn't have the right tab open.

I haven't checked on my MBP yet, but sounds like this is relatively easy to fix. I'll most likely give it a go tomorrow!

**Comment by rfay** [comment]
Could you take a look please @tyler36 ?

**Review by tyler36 — COMMENTED** [review]
Works as stated. Great job!

This watches for hash changes. Could it be update to also check for hashes on page load?

Eg. http://localhost:8000/en/latest/users/quickstart/#drupal should take me to the tab too.

**Comment by rfay** [comment]
Thanks so much for this @mikesnoeren - I think there will be work still to do, and hope you'll keep looking, but I think this gives us a win for the short-term.

**Comment by mikesnoeren** [comment]
No problem! Happy to help :)

I unfortunately haven't found the time to implement the last fixes and am currently away from my MBP for 2 days. If someone could make a new issue with all remaining bugs and assign said issue to me I'll make sure to fix the last bugs asap!

**Comment by rfay** [comment]
New issue 
* #4059 

Thanks!

**Pull request merged**
