### PR TITLE
feat: add DDEV Fig spec generation

### PR DESCRIPTION
**Pull request by khalwat**
## The Problem/Issue/Bug:

This FR automatically generates a [Fig spec](https://fig.io/docs/getting-started) for [Fig](https://fig.io/), as part of the `ddev_gen_autocompletes` command, so it does so as part of the automated build process.

This brings full terminal autocomplete for all Fig commands, with complete inline documentation. The resulting file does nothing on its own, but then you can either [push the spec to the autocomplete repo](https://fig.io/docs/guides/integrating/push-to-autocomplete-action) or [push it to Fig's cloud](https://fig.io/docs/guides/autocomplete-for-internal-tools#4-publish-your-spec).

Then it will be available to everyone who uses Fig.

## How this PR Solves The Problem:

This PR allows us to easily submit a Fig autocomplete for DDEV, so that everyone who uses Fig will benefit.

## Manual Testing Instructions:

Run:
```
make completions
cat .gotmp/bin/completions/ddev_fig_spec.ts
```
To see the resulting generated Fig Spec Typescript file.

## Automated Testing Overview:

No tests are introduced, as I saw no testing being done on the bash/zsh/etc autocomplete files, and the resulting file is just a generated file that does nothing until submitted as mentioned above.

## Related Issue Link(s):

It uses an [officially provided module](https://fig.io/docs/guides/integrating/integrations/cobra) for Cobra to do the work.

## Release/Deployment notes:

Nothing needs to be changed for release/deployment.

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4216"></a>

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
Congrats on the tests being fine! 

These will need to be installed, normally, right? So:

* Can brew install them? They should be added there.
* Can apt install fig completions? They should be added there.
* Docs should explain how to manually install. 
* If it can be pushed to fig's cloud, maybe that should be done by the master build github action?

**Comment by khalwat** [comment]
Manually added a PR to Fig to add the command: https://github.com/withfig/autocomplete/pull/1513

**Comment by khalwat** [comment]
@rfay no, there is nothing to install. The generated file has been PR'd to become part of the Fig repo, so people who use Fig don't have to do anything.

If you want the spec to be auto-updated via CI, you can optionally follow the steps here (I don't have the access/creds to do any of this):

https://fig.io/docs/guides/integrating/push-to-autocomplete-action

...which will re-generate the spec for every version of DDEV, and push it to their repo

**Comment by khalwat** [comment]
If there's anything else you need me to do here, just let me know @rfay

**Comment by rfay** [comment]
I'll go ahead and bring this in. I would certainly like a PR to auto-push to fig. I'm happy to help you figure that out.

**Review by rfay — APPROVED** [review]
Thanks!

**Comment by rfay** [comment]
@khalwat could you please add to the DDEV developer docs step-by-step on how to generate and submit the fig completions? Thanks! It's a nice tool.

**Pull request merged**
