### PR TITLE
Increase EnVar internal buffer to 16K

### LINKED ISSUE #1970: Windows installer: System path destroyed on choco install
**Describe the bug**

I tried to `choco install -y --pre ddev` a couple of times, but failed due to nfsd running. After stopping nfsd, it installed. 

But then I started having trouble, like not being able to find docker.exe, etc.

It turns out that my system PATH had been set to just "C:\Program Files\DDEV" and that's all. Everything else was gone from the PATH.

This was on my real Windows machine, that I don't use terribly often, so it probably hadn't had a chocolatey upgrade recently.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: [e.g. Windows 10, macOS High Sierra]
 - Docker version information (use `docker version`) and insert it here.
 - ddev version information (use `ddev version`)
 - config.yaml contents for the misbehaving project
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
Add any other context about the problem here. Thanks!

### LINKED ISSUE #1971: Windows Installer: Crashes part way through install
**Describe the bug**

On my machine the Windows installer (v1.12.0-rc1) crashes partway through and doesn't get everything installed. The progress bar is about halfway through when it just "goes away". I've repeated this several times.

Here's what actually gets installed before the crash: 
```
$ ls -lR
.:
total 24960
-rwxr-xr-x 1 rfay 197121 25541528 Nov 20 15:41 ddev.exe*
drwxr-xr-x 1 rfay 197121        0 Nov 22 07:11 Icons/
-rw-r--r-- 1 rfay 197121    11357 Nov 20 15:23 license.txt
drwxr-xr-x 1 rfay 197121        0 Nov 22 07:11 Links/

./Icons:
total 36
-rw-r--r-- 1 rfay 197121 34715 Nov 20 15:23 ddev.ico

./Links:
total 5
-rw-r--r-- 1 rfay 197121 53 Nov 22 07:11 'DDEV Documentation.url'
-rw-r--r-- 1 rfay 197121 61 Nov 22 07:11 'DDEV GitHub.url'
-rw-r--r-- 1 rfay 197121 61 Nov 22 07:11 'DDEV Issues.url'
-rw-r--r-- 1 rfay 197121 79 Nov 22 07:11 'DDEV Release Notes.url'
-rw-r--r-- 1 rfay 197121 46 Nov 22 07:11 'DDEV Website.url'
```

This is a physical computer with Windows Insider build 19025, 16GB memory, 190GB free on disk.

### PR DESCRIPTION
**Pull request by gilbertsoft**
## The Problem/Issue/Bug:
Path variables longer than the NSIS string length (default 1024) are not handled by the new used plugin EnVar.

## How this PR Solves The Problem:
This patch changes the size of the internal buffer variable of EnVar from the NSIS string length to 16K to avoid errors with Path variables longer than the size given by the installer.

## Manual Testing Instructions:
Run the installer on a system with a path variable length of 1025 char or more.

## Related Issue Link(s):
Fixes #1970 
Fixes #1971

### CODE REVIEW

**Comment by gilbertsoft** [comment]
@rfay Previously the compiled plugin dll's were included without sources. To not to loose my changes you should not squash commit this PR or we have to split it into two separates PR's

**Comment by rfay** [comment]
@gilbertsoft I'll wait for your instruction, didn't really understand what you were saying. Not sure how squash could lose included artifacts, but I did rebase because this PR wasn't up-to-date with upstream/master.

**Comment by gilbertsoft** [comment]
> 
> 
> @gilbertsoft I'll wait for your instruction, didn't really understand what you were saying. Not sure how squash could lose included artifacts, but I did rebase because this PR wasn't up-to-date with upstream/master.

No, the commit history will be lost and you don't see longer the difference between the original plugin and my changes. Imho it's important we get at least commit 1 and the last. But as said if it's easier and can split this PR into two separates...

**Comment by gilbertsoft** [comment]
I'm closing this PR in favor of #1974

**Pull request closed without merging**
