### PR TITLE
Add LANG default to web and db containers

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

See https://drupal.slack.com/archives/C5TQRQZRR/p1624884000021500

If you try to use text with diacriticals inside the web or DB containers it just fails. 

For example, try to use "äöüÄÖÜßéêè" on the command line in `ddev ssh`

## How this PR Solves The Problem:

This seems to be a problem with the default LANG.

It might be better to do this in the Dockerfile build. 

## Manual Testing Instructions:

`ddev ssh` and then
`ls -l äöüÄÖÜßéêè`

or `echo äöüÄÖÜßéêè > junk.txt` - the text should end up in junk.txt.

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3073"></a>

### CODE REVIEW

**Comment by jonaseberle** [comment]
Tested linux-amd64 from https://github.com/drud/ddev/actions/runs/979171629 ✔️

**Comment by tyler36** [comment]
Confirming Japanese character sets: katakana, hiragana and kanji.

## WSL2 DDEV 1.17.6 -> `ddev ssh`
- ✅　`echo äöüÄÖÜßéêèリンゴ月曜日りんご > junk.txt`
- ❌　` ls -l äöüÄÖÜßéêèリンゴ月曜日りんご` 
```
test-web:/var/www/html$ ls -l äöüÄÖÜßéêèリンゴ月曜日りんご
ls: cannot access ''$'\303\244\303\266\303\274\303\204\303\226\303\234\303\237\303\251\303\252\303\250\343\203\252\343\203\263\343\202\264\346\234\210\346\233\234\346\227\245\343\202\212\343\202\223\343\201\224': No such file or directory
```

## Gitpod
- ✅　`echo äöüÄÖÜßéêèリンゴ月曜日りんご > junk.txt`
- ✅　` ls -l äöüÄÖÜßéêèリンゴ月曜日りんご` 
ddev-utf8


Would love to see this fix as default.

**Comment by jonaseberle** [comment]
@tyler36 it is more about if these characters are supported (enterrable and printable) in the shell at all, not if `ls -l` succeeds.

```
echo äöüÄÖÜßéêèリンゴ月曜日りんご > junk.txt
cat junk.txt
```
might be a better test IMHO

**Comment by tyler36** [comment]
@jonaseberle, just follow OP's "manual testing" steps. 

- the `junk.txt` files were viewable fine on both system, although my comment only included a screenshot for the Gitpod.
- `cat junk.txt` displays characters correctly on WSL2 -> ddev ssh
- `ls -l äöüÄÖÜßéêèリンゴ月曜日りんご` does *not* display correctly on WSL2 -> ddev ssh

**Comment by rfay** [comment]
I do apologize that I revamped the nature of this and would appreciate you testing again. 

The new binaries are at https://github.com/drud/ddev/actions/runs/981425662 or you can just use the gitpod testing technique.

**Comment by jonaseberle** [comment]
Tested linux-amd64 ✔️

**Review by jonaseberle — APPROVED** [review]

**Comment by tyler36** [comment]
Gitpod displays correctly:
```
$ echo äöüÄÖÜßéêèリンゴ月曜日りんご > junk.txt
$ cat junk.txt
äöüÄÖÜßéêèリンゴ月曜日りんご
```

**Pull request merged**
