### PR TITLE
Use buildkite docker-login plugin instead of scripting `docker login`

### PR DESCRIPTION
**Pull request by gilbertsoft**
## The Problem/Issue/Bug:
While working on my PR https://github.com/drud/ddev/pull/3039 there was a login issue with Docker so I was looking for a solution and found the docker-login plugin.

## How this PR Solves The Problem:
So far this looks to perform nice and no login issue occured.

## Release/Deployment notes:

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3041"></a>

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
Looks like an improvement to me. Would have to be in the WSL and macOS environments as well though. I guess this is https://github.com/buildkite-plugins/docker-login-buildkite-plugin - I didn't even really know that buildkite had plugins!

**Comment by gilbertsoft** [comment]
> 
> 
> Looks like an improvement to me. Would have to be in the WSL and macOS environments as well though. I guess this is https://github.com/buildkite-plugins/docker-login-buildkite-plugin - I didn't even really know that buildkite had plugins!

Yeah, saw the failure in my other PR and then found this plugin. Already fixed the other workflows, did see it to late. Will push once the buildkite/ddev-windows-dockerforwindows-nfs step is done.

**Comment by gilbertsoft** [comment]
I've opened an issue for WSL2 see https://github.com/buildkite/agent/issues/1449

**Comment by rfay** [comment]
I chowned /etc/buildkite-agent on the WSL2 test runners to testbot, should solve this problem.

**Comment by gilbertsoft** [comment]
I've opened an issue for WSL2 see https://github.com/buildkite/agent/issues/1449

> 
> 
> I chowned /etc/buildkite-agent on the WSL2 test runners to testbot, should solve this problem.

Do we have self hosted runners here, I have no idea.

**Comment by gilbertsoft** [comment]
> 
> 
> I chowned /etc/buildkite-agent on the WSL2 test runners to testbot, should solve this problem.

Restarted the job and looks plugin installation works now.

**Comment by rfay** [comment]
Login succeeded https://buildkite.com/drud/ddev-wsl2/builds/491#b5f3f9a4-850f-4f93-8bea-78f99922b4e3 line 98

**Comment by gilbertsoft** [comment]
> 
> 
> Login succeeded https://buildkite.com/drud/ddev-wsl2/builds/491#b5f3f9a4-850f-4f93-8bea-78f99922b4e3 line 98

Yep, already close the upstream issue.

**Comment by gilbertsoft** [comment]
Do you have an idea why the Windows test still fails? The login is now fine which was the problem in my other patch but still a failing test afterwards. https://buildkite.com/drud/ddev-windows-dockerforwindows-nfs/builds/3437#ac51b25e-b59e-499a-87d7-3b9d0bc057e6

**Comment by rfay** [comment]
I think I may have resolved that in https://github.com/drud/ddev/pull/3043, it seems to be related to a flaw in time synchronization in Windows Docker Desktop, I've been battling it for a while. Not related to your work.

**Comment by gilbertsoft** [comment]
> 
> 
> I chowned /etc/buildkite-agent on the WSL2 test runners to testbot, should solve this problem.

Did you see the comment https://github.com/buildkite/agent/issues/1449#issuecomment-856804708

**Comment by rfay** [comment]
Of course. Doesn't work very well for WSL2, where you don't have services started as other users. Not systemd.

**Review by rfay — APPROVED** [review]
This is fine, thanks! I'd be interested to know what problem you encountered with `docker login`. 

I'm delaying pulling this because there's an Apple notarization issue in upstream/master that I have to get resolved.

**Comment by gilbertsoft** [comment]
> 
> 
> This is fine, thanks! I'd be interested to know what problem you encountered with `docker login`.
> 
> I'm delaying pulling this because there's an Apple notarization issue in upstream/master that I have to get resolved.

Here is one of the login failures https://buildkite.com/drud/ddev-windows-dockerforwindows-nfs/builds/3435#380d31b6-40bc-4e4f-80bf-7d48cc0d7462

**Comment by rfay** [comment]
Thanks for looking that up.
> dial tcp: lookup auth.docker.io on 192.168.65.5:53: no such host

It's actually a docker DNS failure that haunts especially Windows docker. It's been going on as long as I can remember, with many different name lookups. I've been experimenting with a number of things to try to mitigate it, latest attempt is https://github.com/drud/ddev/commit/25d51f452b0e7b01f1680576c268c5556314580d#diff-ca87371f081edf1d7a27bf5a39af5218c3d99e4c274e7c0fc1f007dbe3774d63R39-R43

**Pull request merged**
