### PR TITLE
Improve handling of `ddev exec`, `ddev composer` and exec hooks by adding `--raw`, fixes #2547

### LINKED ISSUE #2547: 'ddev composer' does not support quotes, making aliases impossible
**Describe the bug**

The way to require a package with an alias, as the [Drupal 9 upgrade documentation](https://www.drupal.org/docs/upgrading-drupal/upgrading-from-drupal-8-to-drupal-9-or-higher) tells you to do, is `composer require "drupal/core:9.0.0 as 8.9.0"`.

However with `ddev composer ...` this results in an error:

```bash
$ ddev composer require "drupal/core:9.0.0 as 8.9.0" --no-update

                              
  [InvalidArgumentException]  
  Could not find package as.  
                              
  Did you mean one of these?  
      ext-hash                
      ramsey/uuid             
      drupal/zen              
      drupal/cog              
      drupal/bfd              
                              

require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

composer [require drupal/core:9.0.0 as 8.9.0 --no-update] failed, composer command failed: exit status 1. stderr= 
```

It seems that ddev composer is stripping out the quotes, which causes "as" to be interpreted as a package name.

**To Reproduce**

1. Have a standard composer-based Drupal 8 ddev installation.
2. Run `ddev composer require "drupal/core:9.0.0 as 8.9.0" --no-update`

**Expected behavior**
I expect composer to add "drupal/core:9.0.0 as 8.9.0" as a requirement in composer.json.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Catalina
- Docker Desktop version: 2.4.0.0
- ddev version information:
  ```
  DDEV-Local version      v1.14.2                                
  commit                  v1.14.2                                
  db                      drud/ddev-dbserver-mariadb-10.2:v1.14.1
  dba                     phpmyadmin/phpmyadmin:5                
  ddev-ssh-agent          drud/ddev-ssh-agent:v1.14.0            
  docker                  19.03.13                               
  docker-compose          1.27.4                                 
  os                      darwin                                 
  router                  drud/ddev-router:v1.14.0               
  web                     drud/ddev-webserver:v1.14.2 
  ```
- config.yaml contents for the misbehaving project
  ```
  type: drupal8
  docroot: htdocs
  php_version: "7.3"
  webserver_type: nginx-fpm
  router_http_port: "80"
  router_https_port: "443"
  xdebug_enabled: false
  additional_hostnames: []
  additional_fqdns: []
  mariadb_version: "10.3"
  provider: default
  project_tld: lmn.gr
  use_dns_when_possible: true
  timezone: Europe/Amsterdam
  disable_settings_management: true
  ```
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?  
  Nothing that I'm aware of. Don't think it would matter for this issue anyway.

**PS**
I realize I'm not on the latest ddev version, but I read the release notes and didn't see anything that would have fixed this meanwhile.

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

People have had an enormous number of problems with complex `ddev exec` and `ddev composer` commands, especially with quotes.

* #2547

There are lots of examples in that issue, and loads of them will need to be tested.

## How this PR Solves The Problem:

* Add `ddev exec --raw`, which will make the exec not use bash to interpret the command. See `ddev exec -h`. `ddev exec --raw -- ls -lR
* Always use raw execution for `ddev composer` or `ddev composer create`. 
* Use raw for shell commands like `ddev drush`
* Add exec_raw to exec hooks:
```yaml
  - exec: 
    exec_raw: [ls, -lR, /var/www/html]
```

## Manual Testing Instructions:

You can use a number of ways to test this PR. Current build is at https://github.com/drud/ddev/actions/runs/1844768190 Probably easiest to use [gitpod](https://gitpod.io/#https://github.com/drud/ddev/pull/3603)

We'll need to add lots of examples to this from #2547
- [ ] Traditional things that worked with `ddev exec`, including bash execution.
  - [x] `ddev exec 'set | grep DDEV'` 
- [x] Exec hooks with and without exec_raw
- [x] Test each provided shell command
  - [x] `ddev mysql -e "SHOW TABLES;"`
  - [x] `ddev psql -c '\l'` and `ddev psql -c 'SELECT * FROM users;'`
  - [x] `ddev php -r 'echo "hi";'`
  - [x] `ddev magento`
  - [ ] `ddev typo3`
  - [ ] `ddev typo3cms`
- [x] Custom command examples
  - [x] @rpkoller's example in https://github.com/drud/ddev/issues/2547#issuecomment-738801282 seems to work now, `ddev drush role-add-perm authenticated 'administer blocks'`, for example.
  - [x] @iamsophiesk's example from https://github.com/drud/ddev/issues/2547#issuecomment-1032634427 `ddev drush sqlq "DELETE FROM key_value WHERE collection = 'update_fetch_task';"` seems to work fine.
- [x] Lots of `ddev composer` examples. 
  - [x] The OP from #2547, `ddev composer require "drupal/core:9.0.0 as 8.9.0" --no-update`
  - [x] @shaal 's example from https://github.com/drud/ddev/issues/2547#issuecomment-899502225 `ddev composer config repositories.feeds '{"type": "path", "url": "repos/feeds", "options": {"symlink": true}}'` now works as is, out of the box, no trouble.

## Automated Testing Overview:

- [x] Still needs tests for several cases of raw.
- [ ] Add tests for `ddev drush` and `ddev mysql` with complex uses

## Related Issue Link(s):

* #2547

## Release/Deployment notes:

- [ ] Users with exotic workarounds to the previous bash-interpreted strings for composer and exec commands will have to simplify them.
- [ ] Alpha testers will have a bad ~/.ddev/commands/web/php that should be removed (and will automatically be replaced)

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3603"></a>

### CODE REVIEW

**Review by shaal — APPROVED** [review]
I tested it with a composer config I use in DrupalPod
Testing this PR, when I use the previous hack -
`ddev composer config repositories.drupal-core1 ' '"'"' {"type": "path", "url": "'"repos/$DP_PROJECT_NAME"'", "options": {"symlink": true}} '"'"' '`
I am getting this error (which is expected)
```
  [Seld\JsonLint\ParsingException]
  "" does not contain valid JSON
  Parse error on line 1:
  ' {"type": "path", "
  ^
  Invalid string, it appears you used single quotes instead of double quotes
```

But when I run the same line without the quotes hack, it works as it should 
`ddev composer config repositories.drupal-core1 '{"type": "path", "url": "repos/$DP_PROJECT_NAME", "options": {"symlink": true}}'`

**Comment by rfay** [comment]
Thanks for that test. I think it would be worth it to people to be able to use `ddev composer config repositories.drupal-core1 '{"type": "path", "url": "repos/$DP_PROJECT_NAME", "options": {"symlink": true}}'` instead of the other thing.

**Comment by rfay** [comment]
Assuming that DP_PROJECT_NAME is defined on the host (what's a decent default value?) then this may work:

`ddev composer config repositories.drupal-core1 "{'type': 'path', 'url': 'repos/$DP_PROJECT_NAME', 'options': {'symlink': true}}"`

That lets bash interpolate the $DP_PROJECT_NAME.

**Comment by shaal** [comment]
@rfay when I run this command 
`ddev composer config repositories.drupal-core1 "{'type': 'path', 'url': 'repos/$DP_PROJECT_NAME', 'options': {'symlink': true}}"`

I get this error
```
[Seld\JsonLint\ParsingException]                                            
  "" does not contain valid JSON                                              
  Parse error on line 1:                                                      
  {'type': 'path', 'url                                                       
  ^                                                                           
  Invalid string, it appears you used single quotes instead of double quotes
```

I tested it on Gitpod using this PR.
I ran first `export DP_PROJECT_NAME=feeds`
and then the `ddev composer config` command, from the `/workspace/d9simple` directory.

**Comment by rfay** [comment]
Please start with `ddev composer config repositories.feeds '{"type": "path", "url": "repos/feeds", "options": {"symlink": true}}'` and work back from there. You'll need to inject your repo name somehow, but that's a problem on the host side. 

I also get your results also with `ddev composer config repositories.feeds "{'type': 'path', 'url': 'repos/feeds', 'options': {'symlink': true}}"`, but your problem is just "how to I inject the project name". There are many ways to do it. You don't have to use an environment variable directly. You can construct the command in stages, adding what you want, then execute it.

The problem you're up against is just how to generate a valid compose string with json in it, and it's something you do on the host with the tools you have available, including concatenation, etc.

**Comment by iamsophiesk** [comment]
Can confirm that this has resolved the issue I was having, and it seems to fix the problem for other examples too. Thanks for jumping on this so quickly. :thumbsup: seems like a neat solution.

**Comment by rfay** [comment]
Thanks for testing @iamsophiesk !

**Comment by jonaseberle** [comment]
Sorry I haven't followed the suggested test regime but I found this to be very resilient. Great!
Stuff that was properly escaped before (`ddev exec 'echo \"a\"'`) will keep working.
This `ddev mysql -e 'SELECT "a"'` works now properly. Same for `ddev composer ".."`.

Although I haven't tested hooks I am confident to give a +1.

**Comment by rfay** [comment]
Thanks to all of you for testing.  I did discover a bug from a previous PR, so please `rm ~/.ddev/commands/web/php` and it will automatically be replaced with the correct version if you get latest here or when the next alpha comes out.

**Comment by rpkoller** [comment]
apologies am a little bit late to the game; haven't noticed the pull request and call for testing. went through a few of the suggested manual tests from the initial post with alpha5. ran into two problems

`ddev php -r 'echo "hi";'` leads to:

```
PHP Parse error:  syntax error, unexpected end of file in Command line code on line 1

Parse error: syntax error, unexpected end of file in Command line code on line 1
```
and `ddev drush role-add-perm authenticated 'administer comment types'` leads to 
```
 Too many arguments, expected arguments "command" "machine_name" "permissions".

Failed to run drush role-add-perm authenticated administer comment types: exit status 1
```
the other two statements i'Ve tried worked: 
ddev exec 'set | grep DDEV'
ddev mysql -e "SHOW TABLES;"

**Comment by rpkoller** [comment]
@rfay you were spot on with your assumption. removing `php` from `.ddev/commands/web` solved the error. after a restart the php echo statement worked!
but about the drush command that still keeps on failing. Either with `administer comment types` or `administer content` like you suggested and i've also tried with `administer blocks` (checked the permissions yaml of the core blocks module beforehand). but all lead to the same `too many arguments` error i've pasted in my previous comment. if i ssh into the container and perform the commands there each of the three works flawlessly. 

*tested on drupal 9.4.x-dev and drush 11.0.5

**Comment by rfay** [comment]
Is it possible you have a customized drush? Please remove any drush from ~/.ddev/commands/web/drush and `<project>/.ddev/commands/web/drush`

**Comment by rpkoller** [comment]
oh! i was under the impression to be able to use `drush` without the need of `exec` or `.` you had to add a global `drush` command using `/var/www/html/vendor/bin/drush $@` inside. that is what i've used and was still there in `~/.ddev/commands/web/drush `. Deleted the file and now the drush commands work as expected!

**Comment by rfay** [comment]
The global drush command has been built into ddev for some time now, but you had created your own a long time ago and ddev respects what people modify if they don't have #ddev-generated in there.

**Comment by rfay** [comment]
Added to caveats in release notes, https://github.com/drud/ddev/releases/tag/v1.19.0-alpha5

**Comment by rfay** [comment]
Oh, I see - you're putting the three parts together:
`ddev composer config repositories.core '{"type": "path", "url": "repos/'"`
+ `"$DP_PROJECT_NAME"`
+ `'", "options": {"symlink": true}}'`


That's a good strategy. Awkward but suitable :)

**Comment by rpkoller** [comment]
@rfay fyi. one observation about a phenomenon i've reported where certain drush commands were hanging indefinitely after being ran successfully. guess i only reported it via dischord and we had a thread there (cant find it right now). but after removing the custom global drush command recommended in relation to this issue here somehow the indefinite hang issue is also gone for a while now! just realised that this morning.

**Comment by rfay** [comment]
Oh, so the problem you had might have been because you had a one-off custom drush command. That's super interesting :)

**Comment by rpkoller** [comment]
buuuut the issue happens again and the commands hang again like before. seems like it was just a temporary improvement and things keep on happening on my setup with the standard global drush command again. just wanted to give you the follow up.

**Comment by rfay** [comment]
I hope you'll be able to create a simple repro case and share it. If you just create a trivial Drupal project with drush and can make this happen it will be solvable. If possible, also try to recreate it on a current-generation computer. Please open an issue when you can recreate it with a demonstration repo+db. You can just push the repro repo up to github and then we'll have something. Thanks!

**Pull request merged**
