### PR TITLE
Custom host and in-container commands, fixes #1372, fixes #1551

### LINKED ISSUE #1372: Hook system overhaul: Access any service, support other commands, user-defined hooks
**Is your feature request related to a problem? Please describe.**

There are a number of oversights in our hook system and fixing them up would make a lot of people happy even if it disrupted their workflow a bit:

* Allow access to any container/service. For example, one should be able to execute an exec hook on the db container, or on an arbitrary npm service. (https://github.com/drud/ddev/issues/1038)
* Allow other post-xxx hooks (like post-composer) (https://github.com/drud/ddev/issues/1071)
* Consider allowing user-defined hooks. (https://github.com/drud/ddev/issues/638)
* Allow custom commands, perhaps based on hooks.
* [Add composer to hook commands #1321](https://github.com/drud/ddev/issues/1321)
* [post hooks like snapshot, snapshot-restore, pre-ssh? #1071 ](https://github.com/drud/ddev/issues/1071)
* [Consider arbitrary commands, and perhaps thus pre and post hooks for those commands #638](https://github.com/drud/ddev/issues/638)
* [Allow users to create and trigger arbitrary hooks](https://github.com/drud/ddev/issues/638) also relates to this.

### LINKED ISSUE #1551: Add a "ddev mysql" command
While `ddev exec --service db mysql` is documented, it would be much easier & faster to type `ddev db` for this. Could you implement it, please?

Thanks!

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

One of many things requested in #1372 and not yet finished was custom commands, so you could write a command with bash or however, and execute it with `dev <customcommandname>`

## How this PR Solves The Problem:

* Allow custom commands on the host, created with a simple script formula and placed in .ddev/commands/host
* Allow custom commands that do their work int he container, simple script in .ddev/commands/web

## Manual Testing Instructions:

* Read the docs. See [current docs](https://github.com/drud/ddev/blob/5fa05b2bb125455538e069e59ed7ee955e4a853c/docs/users/extend/custom-commands.md)
* Review the examples in your project in .ddev/commands/*/*
* Use the examples in .ddev/commands to experiment with both host-side and container-side commands
* Use `ddev` and `ddev <command> -h` to explore the custom commands 
* Use `ddev mysql`

## Automated Testing Overview:

* Added TestCmdCustomCommands, covers quite a bit.

## Related Issue Link(s):

#1372 is ongoing issue that covers this
#1551 requests the "ddev mysql" command, which is provided here.

### CODE REVIEW

**Comment by rfay** [comment]
I would dearly love reviews on this PR as soon as practical. Mostly usage, although always appreciate @andrewfrench going through the go code. But it's usability that is the most important. Current docs at https://github.com/drud/ddev/blob/0d147da83a3826ed6b1053949057579f9acdba94/docs/users/extend/custom-commands.md

I'll post a link to artifacts when they get built.

**Comment by rfay** [comment]
Latest artifacts are at https://circleci.com/gh/drud/ddev/15733#artifacts/containers/0, hope you can take this for a spin gentlemen, @unn, @andrewfrench @cyberswat . I know you're all busy though. I'll proceed with more docs and tests.

**Comment by rfay** [comment]
I went ahead and pulled this, and will ask for review of the prerelease instead, links and artifacts are easier that way.

**Comment by rfay** [comment]
Thanks for taking a look @unn, glad you like it! I think there's quite a bit of maturing to go here, but people will like it. At least some people will. Hopefully there's no reason to hate it.

I didn't completely understand your comment; the current docs of environment variables are at https://ddev.readthedocs.io/en/latest/users/extend/custom-commands/

To study environment variables, a custom command with `set | less` in it makes quick work.

**Comment by unn** [comment]
There is a mismatch between the envars that are available and the documentation.

**Comment by rfay** [comment]
Sorry, I guess you're saying that you'd rather have the web and db container environment variable lists separated?

**Comment by unn** [comment]
`DDEV_XDEBUG_ENABLED` isn't listed in the documentation, for instance. I don't know if the docs are supposed to be a definitive list or not.

**Comment by rfay** [comment]
I left out DDEV_XDEBUG_ENABLED because I didn't think it was useful. Actually it seemed to me like most of them weren't all that useful.

**Comment by unn** [comment]
Ah got it, the list in the docs isn't suppose to be definitive, it sounds.

**Pull request merged**
