### PR TITLE
Harden Drupal version detection #545

### PR DESCRIPTION
**Pull request by mglaman**
## The Problem/Issue/Bug:

Detecting the Drupal version can be weak if wrong docroot chosen.

## How this PR Solves The Problem:

There must be an `index.php` and contain the word "Drupal", then follow structure patterns.

### CODE REVIEW

**Comment by rickmanelius** [comment]
Added reviewers and placed on our project board.

**Comment by rickmanelius** [comment]
I'll wait for @rfay to take a first pass on code/tests before I jump in.

**Comment by rfay** [comment]
* I'm not convinced that this adds significant value over what was there before.
* We've been trying to deliberately treat d6/d7/d8 as separate things and not mix the code, so it's easier to maintain (despite some copying).

So I'm uncomfortable with this one.

**Comment by mglaman** [comment]
@rfay  that's fine, we can close. The main thing is the `index.php` peek to ensure it's Drupal. That might help with other CMS support down the road. "We know that a file within X bytes will say its name"

**Comment by rfay** [comment]
Thanks, sorry. I hate to have people spend time on things and it turn out not used. But it's just a different direction than the code has been going. Thanks so much for your absolutely excellent contributions on so many fronts.

**Pull request closed without merging**
