### PR TITLE
Switch to mariadb

### PR DESCRIPTION
**Pull request by cweagans**
## The Problem/Issue/Bug:

We're switching to mariadb. The container is ready to roll, so now we need to test it with ddev.

## How this PR Solves The Problem:

ddev now uses a provisional tag from the drud/mariadb-local docker repo.

## Manual Testing Instructions:

`ddev config && ddev start` on a site that doesn't already have a docker-compose.yml. Everything should work as it did with the mysql image.

## Automated Testing Overview:

No tests were added - this is just the ~simple~ image swap.

## Related Issue Link(s):

https://github.com/drud/ddev/issues/488
https://github.com/drud/docker.mysql-local/pull/30

### CODE REVIEW

**Comment by cweagans** [comment]
Rebased onto master.

**Comment by cweagans** [comment]
Windows errors:

```
Starting mysqld. 
chown: cannot access '/var/log/mysqld.log': No such file or directory
2017-12-19 22:30:04 139880363964288 [Note] mysqld (mysqld 10.2.11-MariaDB-10.2.11+maria~jessie-log) starting as process 1 ...
2017-12-19 22:30:04 139880363964288 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2017-12-19 22:30:04 139880363964288 [Note] InnoDB: Uses event mutexes
2017-12-19 22:30:04 139880363964288 [Note] InnoDB: Compressed tables use zlib 1.2.8
2017-12-19 22:30:04 139880363964288 [Note] InnoDB: Using Linux native AIO
2017-12-19 22:30:04 139880363964288 [Note] InnoDB: Number of pools: 1
2017-12-19 22:30:04 139880363964288 [Note] InnoDB: Using SSE2 crc32 instructions
2017-12-19 22:30:04 139880363964288 [Note] InnoDB: Initializing buffer pool, total size = 1G, instances = 8, chunk size = 128M
2017-12-19 22:30:04 139880363964288 [Note] InnoDB: Completed initialization of buffer pool
2017-12-19 22:30:04 139878893319936 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2017-12-19 22:30:04 139880363964288 [ERROR] InnoDB: The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages!
2017-12-19 22:30:04 139880363964288 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2017-12-19 22:30:05 139880363964288 [Note] InnoDB: Starting shutdown...
2017-12-19 22:30:05 139880363964288 [ERROR] Plugin 'InnoDB' init function returned error.
2017-12-19 22:30:05 139880363964288 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2017-12-19 22:30:05 139880363964288 [Note] Plugin 'FEEDBACK' is disabled.
2017-12-19 22:30:05 139880363964288 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
2017-12-19 22:30:05 139880363964288 [ERROR] Unknown/unsupported storage engine: InnoDB
2017-12-19 22:30:05 139880363964288 [ERROR] Aborting
```

**Comment by cweagans** [comment]
Looks like there might be some change in behavior around the innodb_flush_method param. In mysql, the default is fsync, but mariadb appears to use o_direct for some things, which would definitely cause a problem for a windows mount. 1aea116 is an attempt at resolving this by setting innodb_flush_method=fdatasync (renamed in mariadb).

**Comment by cweagans** [comment]
After a lot of research, testing, and debugging, I think we have a few options here (roughly in order of my preference):

1. Drop Docker for Windows support (recommend docker toolbox instead)
2. Use a different storage engine.
3. Stop doing host mounts for database volumes.
4. Convince Docker to open source Docker for Windows so that we can dig in and attempt to fix their filesystem stuff.
5. Don't switch to MariaDB.

**Comment by rfay** [comment]
Please update here with the simple docker command used to demonstrate the #fail on Windows. Thanks!

**Comment by rfay** [comment]
It also seems that we must be missing a test on the drud/mariadb-local to demonstrate this, because we should have detected the problem long before we had to see it here.

**Comment by cweagans** [comment]
`docker run -v "C:\\Users\\me\\Downloads\\mariadb-tests\\mysql:/var/lib/mysql" -eMYSQL_ROOT_PASSWORD=root mariadb:10.2`

`docker run -v "C:\\Users\\me\\Downloads\\mariadb-tests\\mysql:/var/lib/mysql" -eMYSQL_ROOT_PASSWORD=root mariadb:10.1`

`docker run -v "C:\\Users\\me\\Downloads\\mariadb-tests\\mysql:/var/lib/mysql" -eMYSQL_ROOT_PASSWORD=root mariadb:10.0`

These all fail on windows ^

If I change the `default_storage_engine` in my.cnf to Aria or MyISAM and replace the default one in the container, any of the above commands will succeed. 


I think that we should seriously consider switching away from host mounts for persistence. The contents of /var/lib/mysql aren't very useful in isolation. If we just let docker manage the volumes for /var/lib/mysql, the contents of the database will persist until the user removes the environment. For portability of data, adding a `ddev export-db` would be fairly straightforward. This would ensure that we will never run into filesystem issues like this again, since all of that stuff would live inside the VM. It might make things a bit more snappy as well, since we won't have to do the additional Samba/OSXFS hop before the data actually gets to or from the disk (for the database, specifically). Additionally, if we had an `export-db` command, it wouldn't be difficult to automatically dump a copy of the database to disk at the point where an environment is removed.

Personally, I don't have a lot of faith in the idea of just tabling the idea of switching to MariaDB until MariaDB is fixed. The MariaDB devs don't seem to be aware of the issue - probably because nobody in their right mind would mount a Samba share at /var/lib/mysql outside of Docker for Windows. We can submit a bug report, but I don't think anyone is going to be too excited about a finding a resolution for that problem beyond "Don't do that!".

**Comment by rickmanelius** [comment]
We finished a video chat on this and the conclusion is that while we are very much in favor of these recommendations (specifically switching to Docker volumes as long as we have a friendly way to export/revert from local backups similar to what is being stubbed out here https://github.com/drud/ddev/issues/467), the fact is that this adds a considerable amount of additional engineering effort due to these dependencies and doesn't provide significant gain to the end-user by itself. However, I very much want to pursue the snapshot/backups ideas, which would then allow us to adjust & apply this work further down the timeline.

**Comment by cweagans** [comment]
So the follow ups here are:

* Investigate switching back to plain docker volumes for database persistence (no more host mounts)
* Make sure MariaDB folks know about InnoDB issues on Samba mounts (unlikely to do anything, but we spent the time figuring out the issue -- we might as well let upstream know)
* Add an `export-db` subcommand to ddev as easy low-hanging fruit for snapshotting
* Investigate a nicer snapshotting method (`ddev create-snapshot`, `ddev revert [snapshot id]`?)
* Rename local MySQL container repo back to what it was before
* Delete drud/mariadb-local docker repo

Closing this since we're not gonna merge it.

**Comment by cweagans** [comment]
Oh, also:

* https://github.com/drud/ddev/pull/572/commits/82fc8f98153aee439d6ee4bdb2cf047e09853d2f and https://github.com/drud/ddev/pull/572/commits/5823a29358cb731ef286abfd3592d27fd5068293 are both worthwhile changes, so we should merge those in separately.

**Comment by rfay** [comment]
Some notes on the sources explaining this problem:

https://github.com/docker-library/mariadb/issues/95 is a key issue in library/mariadb that explains where lots of people have had the same problem.

List of working and non-working docker images: https://github.com/docker-library/percona/issues/42#issuecomment-298109103

**Pull request closed without merging**
