### PR TITLE
✨ bookmarklet support for Gitlabs & Bitbucket repos

### PR DESCRIPTION
**Pull request by tyler36**
## The Problem/Issue/Bug:
DDEV-gitpod bookmarklet does not support non-github "git repositories"

## How this PR Solves The Problem:
This PR uses a regex expression to check for the 3 main repos
- [x] Github - checks for "https://github.com"
- [x] Gitlab - checks for "https://gitlab.com"
- [x] Bitbucket - checks for "https://bitbucket."

Note:
- I don't use bitbucket or gitlab on a regular basis.

Bitbucket
- I did a search for bitbucket pulic repos and came across https://bitbucket.csiro.au/repos?visibility=public
- Thought I might aswell expand support for non-"https;//bitbucket.org" repos
- Not sure if github or gitlabs uses a similar thing

## Manual Testing Instructions:

- Add bookmarklet

### Github
- Visit https://github.com/rfay/randyfay.com

### Gitlabs
- Visit https://gitlab.com/weitzman/drupal-test-traits

### Bitbucket
- Visit https://bitbucket.csiro.au/users/bat161/repos/pytorch_unet/browse

## Related Issue Link(s):

#3451

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3465"></a>

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
Thanks for this! 

* I wasn't able to get the bitbucket example to work. DDEV_REPO came out to `https://bitbucket.csiro.au/users/bat161/repos/pytorch_unet/browse`but it should be `https://bitbucket.csiro.au/users/bat161/repos/pytorch_unet` - the problem is just that bitbucket has a slightly different URL structure and I guess you have to pull out the "browse" (or not try it, which is also valid).
* Please don't use the master branch of your fork for PRs, as it just makes a mess the next time. Please use a branch devoted to the PR. For example, `git fetch upstream && git checkout -b 20211226_unique_pr_branch upstream/master --no-track` where upstream is the name of the drud/ddev remote.  There's no need to change this for this PR.

**Comment by tyler36** [comment]
Your right, the bitbucket repo doesn't seem to pull down. When I "tested", it was basically making sure the page loaded but it seems the repo isn't even cloned.

I did a quick survey of co-workers that use bitbucket and did a search for other public repos.
A more "standard" repo seems to follow the following format where:
[https://bitbucket.org/hyrioo-public/laravel-hyper-api/src/master/](https://bitbucket.org/hyrioo-public/laravel-hyper-api/src/master/)

- `hyrioo-public` is the username
- `laravel-hyper-api` is the repo name
- `master` is the branch name

So after playing around this morning, I think the best approach for Bitbucket will be in the ddev-gitpod-launch repo. 
It's failing because the [`git clone` ](https://github.com/drud/ddev-gitpod-launcher/blob/0d334410f07c6725beb835b7fbb103b2c60a6969/.gitpod/start_repo.sh#L16) line doesn't have a valid `reponame`

## TEST
Visit the following repos, and click the bookmarklet

- https://bitbucket.org/hyrioo-public/laravel-hyper-api/src/master/
```shell
$ echo ${DDEV_REPO} 
https://bitbucket.org/hyrioo-public/laravel-hyper-api/src/master/
$ echo ${DDEV_REPO##*/}

$
```

- https://github.com/rfay/randyfay.com
```shell
$ echo ${DDEV_REPO}
https://github.com/rfay/randyfay.com

$ echo  ${DDEV_REPO##*/}
randyfay.com
```

Bitbucket offers a 2 options for clone:
- `git clone git@bitbucket.org:hyrioo-public/laravel-hyper-api.git`
- `git clone https://hyrioo-public@bitbucket.org/hyrioo-public/laravel-hyper-api.git`

But using the direct URL also seems to work
- `git clone https://bitbucket.org/hyrioo-public/laravel-hyper-api/src/master/`

I think the bookmarklet functions correctly, but we could improve parsing in [start_repo.sh](https://github.com/drud/ddev-gitpod-launcher/blob/0d334410f07c6725beb835b7fbb103b2c60a6969/.gitpod/start_repo.sh) 

- Detect if `DDEV_REPO` is bitbucket
- If so, extract reponame


Perhaps you could run a Twitter poll and find out how many people use BitBucket, and what their "standard" url is.

**Comment by rfay** [comment]
I didn't completely understand you: Are you saying "let's drop bitbucket"? That's fine. Do we need changes then?

**Comment by tyler36** [comment]
I submitted a PR to ddev-gitpod-launcher, https://github.com/drud/ddev-gitpod-launcher/pull/17 .

Assuming that PR is accepted, this PR should be good to merge as is.

**Comment by rfay** [comment]
Sorry, as over there, I don't think guessing the default branch will work out.  Thanks for your work on this. And if it needs to go without bitbucket support for now that will be OK.

**Comment by tyler36** [comment]
Moving to #3526

**Pull request closed without merging**
