### PR TITLE
[FEATURE] Introduce Windows User Installer, fixes #1914

### LINKED ISSUE #1914: Provide a user installer for Windows
**Is your feature request related to a problem? Please describe.**
Nowadays more and more development related products provide an user installer which installs the product to the user profile instead of the normal program files folder. This has some advantages in business environments where the user not always has the right to install products to the program files folder.

## To Do

- [ ] Sign uninstaller (#1898)
- [ ] Provide download and install images tarballs (#1922)
- [ ] Bundle ngrok with the Windows installer (#1925 )
- [ ] Add Windows ddev bash completion capability to installer (#1934)
- [ ] Uninstaller should stop running processes (winnfsd) before performing the uninstall (#1945)
- [ ] Evaluate: system restart after docker install (#1989)
- [ ] Update docs (#1990)
- [ ] Provide a separate Chocolatey installer (#1991)
- [ ] Optimize or remove Docker Desktop (#1992)
- [ ] Move all license pages before components selection
- [ ] Extract includes (DDEV and Docker) to https://github.com/GsNSIS/

### PR DESCRIPTION
**Pull request by gilbertsoft**
## The Problem/Issue/Bug:

#1914: Provide "user" installer for Windows

### CODE REVIEW

**Comment by rfay** [comment]
I wouldn't think you'd open this until the other one was pulled.

**Comment by gilbertsoft** [comment]
> 
> 
> I wouldn't think you'd open this until the other one was pulled.

Oh yes, it's based on the other one and almost running. Needs some minor improvments

**Comment by rfay** [comment]
This one's going to get obsolete by work on the main installer right? Should this be closed and have a start-over version when the time comes to work on it again?

**Comment by rfay** [comment]
I'm going to take the liberty of termporarily closing this per @gilbertsoft 's approval to do so. It can be resurrected when there's time to push it forward. This PR can just be reopened.

**Pull request closed without merging**
