### PR TITLE
[docs] Add more instructions on how to opt-in/out to stats usage.

### PR DESCRIPTION
**Pull request by ElijahLynn**
## The Problem/Issue/Bug:
Clarify the exact setting to use to opt-in/out to stats usage.

## How this PR Solves The Problem:
Adds instructions. 

## Release/Deployment notes:

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3911"></a>

### CODE REVIEW

**Review by rfay — APPROVED** [review]
Thanks - looks good to me. I'd be interested to know what prompted you to explore this territory and whether it was hard to figure out.

**Comment by ElijahLynn** [comment]
> Thanks - looks good to me. I'd be interested to know what prompted you to explore this territory and whether it was hard to figure out.

I was helping configure ddev to run in codespaces and saw the prompt was hanging the script, and ended up following the link at the prompt and noticed that was confusing because it said where to set it but not what to set.

**Comment by rfay** [comment]
I hope you'll contribute back your codespaces work. I've spent some time with that and was successful, but didn't want to completely go down that rabbit-hole.

Note that if you don't want any interruptions of this type, use `ddev start -y`.

**Comment by ElijahLynn** [comment]
> I hope you'll contribute back your codespaces work. I've spent some time with that and was successful, but didn't want to completely go down that rabbit-hole.
> 
> Note that if you don't want any interruptions of this type, use `ddev start -y`.

Thanks, I didn't think to try `ddev start -y`, maybe I'll do that instead. 

Work will be public after this is merged https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9401.

**Pull request merged**
