### PR TITLE
Fix typo in custom-commands documentation

### PR DESCRIPTION
**Pull request by andy-blum**
## The Problem/Issue/Bug:
Typo in documentation

## How this PR Solves The Problem:
Fixed typo

### CODE REVIEW

**Comment by andy-blum** [comment]
Clicking the link to the CLA already populates all my info in. 🤔

**Comment by andy-blum** [comment]
Somewhere along the line my git config was edited and had the email address `ter`, which github won't allow me to add to my account.

Can the CLA be bypassed or do I need to delete this PR and re-submit with a real email address?

**Comment by rfay** [comment]
I think you can just `git commit --amend --author="Author Name <email@address.com>" --no-edit` and then `git push --force-with-lease`

**Comment by andy-blum** [comment]
"just" 😂

I'll give it a shot.

**Pull request merged**
