### PR TITLE
Fixed typos in command line and comments

### PR DESCRIPTION
**Pull request by stasadev**

### CODE REVIEW

**Review by rfay — APPROVED** [review]
Awesome, thanks!

**Comment by rfay** [comment]
Interested in how you detected these as well. Maybe new check for builds.

**Comment by stasadev** [comment]
It's a [Grazie](https://plugins.jetbrains.com/plugin/12175-grazie) spell checker by JetBrains, that uses [LanguageTool](https://languagetool.org/) under the hood.

**Comment by rfay** [comment]
Well, awesome work. Looks like it's not possible to integrate into a CI build though? Sure do appreciate your eye on this stuff!

**Comment by stasadev** [comment]
Yes, I think it is not possible to integrate because it also detects typos in words like mkcert, dbserver, docroot, etc. It is not possible to add every word to the dictionary.

**Pull request merged**
