### PR TITLE
Better version suggestion

### PR DESCRIPTION
**Pull request by AronNovak**
## The Problem/Issue/Bug:
#1706 

## How this PR Solves The Problem:
Provides two ways to encourage the user to upgrade DDEV (config).

## Manual Testing Instructions:
Downgrade local DDEV, execute on a latest configfile and check the warning message.

## Automated Testing Overview:
Tests would be nice to add later.

## Related Issue Link(s):
#1706 

## Release/Deployment notes:
No changes are needed on the user side.

### CODE REVIEW

**Comment by AronNovak** [comment]
The PR still needs some love. Better code styling / formatting. Possibly some tests.

**Comment by rfay** [comment]
Thanks!

**Comment by AronNovak** [comment]
Tested in a separate Go file for the sake of simplicity:
```go
package main

import "fmt"
import "strings"
import "strconv"

func compareVer(a, b string) (ret int) {
  as := strings.Split(a, ".")
  bs := strings.Split(b, ".")
  loopMax := len(bs)
  if len(as) > len(bs) {
    loopMax = len(as)
  }
  for i := 0; i < loopMax; i++ {
    var x, y string
    if len(as) > i {
      x = as[i]
    }
    if len(bs) > i {
      y = bs[i]
    }
    xi,_ := strconv.Atoi(x)
    yi,_ := strconv.Atoi(y)
    if xi > yi {
      ret = -1
    } else if xi < yi {
      ret = 1
    }
    if ret != 0 {
      break
    }
  }
  return
}


func main() {
  APIVersion := "v1.9.0"
  DdevVersion := "v1.9.1."

  if compareVer(APIVersion, DdevVersion) == 1 {
          fmt.Print("ddev config")
  } else if compareVer(APIVersion, DdevVersion) == -1 {
          fmt.Print("ddev upgrade")
  }
}
```

image

**Comment by rfay** [comment]
Looks like you've about got it! All go code needs to be gofmt'd, so much better than the php way, no arguments ever about code formatting. `make staticrequired` will show you any problems in advanced. `gofmt -w -s <filename.go>` will fix up the file.

**Comment by AronNovak** [comment]
@rfay Ready for review. Let me know if you prefer to have a basic test for it.

**Comment by AronNovak** [comment]
Test the logic in an isolated file:
image

**Comment by AronNovak** [comment]
@rfay So please review the current status and let me know if it still needs a bit of work. Thanks!

**Comment by rfay** [comment]
Please rebase this against current master, or ask me to do it, thanks.

**Comment by AronNovak** [comment]
@rfay Sure, it's rebased now.

**Comment by rfay** [comment]
And a minor comment on what we should do with that error message, just thinking out loud.

It has been more than a year since the APIVersion in the config.yaml actually meant anything or broke anything.

OTOH, we really should be using it for some things. In v1.10.0, older pinned webimage and dbimage versions were all broken, and we could have caught that by checking the APIversion (or at least looking at the webimage/dbimage versions. Also, we should could force a stop/start==restart when we see an obvious ddev upgrade happening. Those aren't in scope for this PR, I'm just thinking about what we're doing and why.

**Comment by rfay** [comment]
I tested this locally, and I think that you did mean to have different error messages and don't at this point.

I took the liberty of rebasing against current master and pushing it into your branch, so you'll want to reset to the rebased fetched remote.

**Comment by AronNovak** [comment]
Thanks for the test, I continue according to your advice above!

**Comment by rfay** [comment]
Thanks for working on this. I'm sorry for the CircleCI build failure, has nothing to do with your code. Silly chocolatey has weird version requirements and we've entered into the twilight zone with them again. But the buildkite tests should give a good indication.

**Comment by AronNovak** [comment]
Thanks. It took me a little time to make sure I can compile my own DDEV, as `make` behaved weirdly, it seemingly did nothing, then I realized that first it fetches a large Docker image before doing anything. Anyways, now I have the ability to confirm locally that with a real DDEV configfile, it gives the appropriate, different messages in both scenarios.

**Comment by AronNovak** [comment]
The original scenario works well:
image

The scenario where DDEV needs an upgrade:
image

**Comment by AronNovak** [comment]
@rfay So it seems the goal is reached, could you review it now, with one comparison only?

**Comment by rfay** [comment]
@AronNovak should we change the wording and say something like "version mismatch" or something?

**Comment by rfay** [comment]
I made minor verbiage changes, thanks so much for all your work on this. Let's get it in :)

**Comment by rfay** [comment]
Thanks so much for the hard work on this @AronNovak !

**Comment by AronNovak** [comment]
@rfay Thanks! I was thinking on how to defend the fact to print out different messages in different scenarios. I think it's mostly relevant for teamwork, and only for such edge cases when a functionality is used what was introduced by a later DDEV version - that's of course not typical.

Thanks for not abandoning this PR!

**Pull request merged**
