### PR TITLE
WIP Use Buildkite for macOS and Windows testing

### PR DESCRIPTION
**Pull request by cweagans**
## The Problem/Issue/Bug:

We're switching to Buildkite. This PR will contain the necessary changes to make it happen.

### CODE REVIEW

**Comment by cweagans** [comment]
Do we need to keep Surf around? I thought the idea was to replace Surf with Buildkite. Are you saying that you want to run them in parallel for a while?

**Comment by rfay** [comment]
There's no intent to keep surf, but imo it never helps to burn your bridges during development. Better to get the new thing in place without destroying the old, then retire the old.

**Comment by cweagans** [comment]
Fair enough. I can get behind that. Probably going to change up the approach here a bit anyhow, so it shouldn't interfere with the surf stuff. I've got some other things to do before I can get back to this though, so it'll be a bit before that happens.

**Comment by rfay** [comment]
I fully support this, but there's no expectation that it will be completed soon, so I'm going to temporarily close it, we'll reopen when it's time to work on it again.

**Pull request closed without merging**
