### PR TITLE
Fix various errors in typo3 and typo3cms global commands, add wp command, fixes #2467

### LINKED ISSUE #2467: A global wp command (wp-cli)
**Describe the solution you'd like**

```
#!/bin/bash

## Description: Run WordPress CLI inside the web container
## Usage: wp [flags] [args]
## Example: "ddev wp core version" or "ddev wp plugin install user-switching --activate"
## ProjectTypes: wordpress

wp "$@"
```

### PR DESCRIPTION
**Pull request by gilbertsoft**

### CODE REVIEW

**Comment by rfay** [comment]
Pushed a commit to pack it into the binary.

Glad you checked those out! 

The alpha1 release was a mistake. I must have pushed the wrong button :(

**Comment by rfay** [comment]
Since I was fiddling with packr2 and #2467 came in I hope you don't mind my hijacking this to add that in here. It's worth doing the packr2 as little as possible.

**Comment by gilbertsoft** [comment]
> The alpha1 release was a mistake. I must have pushed the wrong button :(

I already thought so because it's not marked as pre release :(

**Comment by rfay** [comment]
I did notice and check the prerelease button.

**Comment by gilbertsoft** [comment]
> 
> 
> Since I was fiddling with packr2 and #2467 came in I hope you don't mind my hijacking this to add that in here. It's worth doing the packr2 as little as possible.

Yeah this one came up today in Slack and I advised the user to open an issue for this as it looks WP CLI should be included also. No problem with your hijacking ;)

**Pull request merged**
