### PR TITLE
Basic building with WIndows for #196

### PR DESCRIPTION
**Pull request by rfay**
## The Problem:

We want to consider support windows for ddev per https://github.com/drud/ddev/issues/196

## The Fix:

* Add windows target to Makefile (This is actually accomplished in upstream https://github.com/drud/build-tools/pull/25, which will overwrite the minor change here when it comes in)
* Add vendoring necessary to build for windows.
* Support $DOCKER_HOST and related environment variables, which we may hit in various contexts
* Remove the assumption of docker being on localhost and parse $DOCKER_HOST to get it.
* Support TLS connection with docker, not just http.
* Improve prepLocalSiteDirs() and move it into ddevapp/config.go, which is the only remaining user; run it on config new.
* Minor test changes to account for the change in calling prepLocalSiteDirs() (.ddev/data is created earlier)
* If sudo is not available, tell people what to do to add the hosts entry.

Although it looks to me like these are all reasonable long-term changes for ddev (not particularly related to windows and our decision on it) I"m not attached to any of them, so if the team wants to leave any of these behind I'll rework.

With this PR you can `make windows` to build into bin/windows/windows_amd64/ddev.exe

In addition, all 3 binaries (OSX, Linux, Windows) are now pushed into the circle test page:

drud_ddev__752_-_circleci

## Related Issue Link(s):

* #196 [Decisions and Plan for Linux and WIndows Support](https://github.com/drud/ddev/issues/196)
* Cross-compile failure on go-winio: https://github.com/Microsoft/go-winio/issues/52

## Release/Deployment notes:

This *builds* for windows. The resultant executable and its operation are a completely different topic.

### CODE REVIEW

**Comment by rfay** [comment]
I think this is ready for review, and that there's really nothing here that is Windows specific. I think it should generally be improvements. This currently runs on Windows using the ddev.exe under cmd and with docker toolbox (regular windows version). It gets messed up if you run in any environment that translates paths.

**Comment by rickmanelius** [comment]
@rfay Curious. I went to https://circleci.com/gh/drud/ddev/752 and did not see the "artifacts" tab. Does that require being logged in to access?

**Comment by rfay** [comment]
@rickmanelius do you not see the tab? Please try logging into circle. It's just a matter of authorizing login via github. Sorry I didn't know that was privileged.

**Comment by rickmanelius** [comment]
@rfay that worked 👍  I hadn't yet explored Circle's user/registration process and I didn't know if this might result in an extra license against an account.

**Comment by rfay** [comment]
Rebased to current, with one conflict. I think if this runs ok on Windows and passes the tests here it can come in. I'll work on getting windows tests to run and solving shell-out problems in a separate PR.

**Pull request merged**
