### PR TITLE
Update Drush version from 8.3.1 to 8.3.2, fixes #1999

### LINKED ISSUE #1999: Update drush version to 8.3.2
**Describe the bug**
When I did `drush make`-command; I got the error such as:
```
truls1502$ ddev ssh
truls1502@web:/var/www/html/web$ drush make ../site.make
Make new site in the current directory? (y/n): y
include(phar:///usr/local/bin/drush8/vendor/composer/../../src/Internal/Symfony/Yaml/Yaml.php): failed to open stream: phar error:        [warning]
"src/Internal/Symfony/Yaml/Yaml.php" is not a file in phar "/usr/local/bin/drush8" ClassLoader.php:444
include(): Failed opening 'phar:///usr/local/bin/drush8/vendor/composer/../../src/Internal/Symfony/Yaml/Yaml.php' for inclusion           [warning]
(include_path='.:/usr/share/php') ClassLoader.php:444
PHP Fatal error:  Class 'Drush\Internal\Symfony\Yaml\Yaml' not found in phar:///usr/local/bin/drush8/lib/Drush/Make/Parser/ParserYaml.php on line 26
Fatal error: Class 'Drush\Internal\Symfony\Yaml\Yaml' not found in phar:///usr/local/bin/drush8/lib/Drush/Make/Parser/ParserYaml.php on line 26
Drush command terminated abnormally due to an unrecoverable error.                                                                        [error]
Error: Class 'Drush\Internal\Symfony\Yaml\Yaml' not found in phar:///usr/local/bin/drush8/lib/Drush/Make/Parser/ParserYaml.php, line 26
```

After talked on #drush-channel and they mentioned the issue should be resolved on [Drush version 8.3.2](https://github.com/drush-ops/drush/releases/tag/8.3.2). 
So [this line](https://github.com/drud/ddev/blob/v1.12.0/containers/ddev-webserver/Dockerfile#L7) needs to be fixed.

So I tried to add a new file `.ddev/web-build/Dockerfile` with below:
```
ARG BASE_IMAGE=drud/ddev-webserver:v1.12.1
FROM $BASE_IMAGE

ENV DRUSH_VERSION=8.3.2

RUN curl -sSL "https://github.com/drush-ops/drush/releases/download/${DRUSH_VERSION}/drush.phar" -o /usr/local/bin/drush8 && chmod +x /usr/local/bin/drush8
```

Then it is working smooth now. 

**To Reproduce**
1. `ddev config --project-name="DrushMake"  --project-type="drupal7" --php-version="5.6"`
2. `ddev start && ddev exec drush make site.make` (You need a make file).

**Expected behavior**
It shouldn't throw such error.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS Catalina
 - Docker version:
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### PR DESCRIPTION
**Pull request by truls1502**
Related #1999

### CODE REVIEW

**Comment by rfay** [comment]
@truls1502 you don't seem to have given me permission to push into this, so you'll need to bump the version.go to point to the webimage I have pushed for you. All you have to do is change the WebTag in pkg/version/version.go :

```
commit 9190c9d84918e5ec4fd576102aed170933cd39a8
Author: Randy Fay <randy@randyfay.com>
Date:   Thu Dec 12 10:58:11 2019 -0700

    Bump version to point to new container

diff --git a/pkg/version/version.go b/pkg/version/version.go
index 5d43742b..c6172b02 100644
--- a/pkg/version/version.go
+++ b/pkg/version/version.go
@@ -49,7 +49,7 @@ var DockerComposeFileFormatVersion = "3.6"
 var WebImg = "drud/ddev-webserver"
 
 // WebTag defines the default web image tag for drud dev
-var WebTag = "v1.12.1" // Note that this can be overridden by make
+var WebTag = "20191212_truls_drush" // Note that this can be overridden by make
 
```

**Comment by rfay** [comment]
Did you see that this is number 2000! Celebration!

**Comment by truls1502** [comment]
> Did you see that this is number 2000! Celebration! 

Ahh, it is a nice number! 🎉👍😍

**Comment by rfay** [comment]
Thanks so much for this!

**Pull request merged**
