### PR TITLE
Platform.sh and generic hosting provider integration, fixes #2384, fixes #2194

### LINKED ISSUE #2194: Allow user-provided provider for alternate hosting providers to push/pull/etc
**Is your feature request related to a problem? Please describe.**
`ddev pull` is one of my favorite features to use with our pantheon-hosted sites, but I wish we had that capability for sites that are hosted on other providers

**Describe the solution you'd like**
I don't have a fully-baked idea of how this would work, but my initial thoughts would be to include a yaml file similar to the following:
```yml
environments:
  dev:
    connection_type: direct
    db:
      host: 127.0.0.1
      username: db
      password: db
      database: db
      port: 3306
  test:
    connection_type: direct
    db:
      host: proof.example.com
      username: db
      password: db
      database: db
      port: 3306
  live:
    connection_type: ssh
    ssh:
      host: example.com
      username: admin
      password: pass
      key: ~/.ssh/id_rsa.pub
      port: 
    db:
      host: localhost
      username: db
      password: db
      database: db
      port: 3306
```
and to include this in the config file with `provider: path/to/environments.yml`.

In this project running ddev pull would export a copy of the DB to the local machine and then import it into the project

### LINKED ISSUE #2384: Implement platform.sh integration
Pantheon and ddev-live have explicit integration in ddev. Platform.sh should have it too!

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

Support platform.sh hosting #2384 
User-provided hosting provider integration #2194 

## How this PR Solves The Problem:

New provider technique with a custom yaml file in .ddev/providers

## Manual Testing Instructions:

- [ ] Platform.sh
1. Create an account on platform.sh, get the API token.
2. Follow the instructions in the .ddev/providers/platform.example to set up
3. `ddev pull platform`
4. Verify that the pulled database and files are correct.

- [ ] Flatfile
* Use the flatfile.yaml.example to set up db and files imports
* Try it out

## Automated Testing Overview:

* Added TestPlatformPull
* Added TestFlatfilePull

### CODE REVIEW

**Comment by andy-blum** [comment]
If I'm reading this correctly, the flatfile yml is reliant on having DB snapshots already taken, yes?

Is there a way for DDEV to connect to a database to take its own snapshot?

**Comment by rfay** [comment]
It has nothing to do with ddev snapshots. I don't understand what you're saying. If you're talking about pulling from the upstream database, yes, it pulls from the live database. 

If you'd like to try this now, the artifacts are at https://app.circleci.com/pipelines/github/drud/ddev/3655/workflows/393267d7-f898-4646-a647-80b8982c86b0/jobs/31142/artifacts and the docs are at https://ddev.readthedocs.io/en/latest/users/providers/platformsh/ - otherwise, I hope to have an alpha that includes this next week.

**Comment by rfay** [comment]
It does a `platform db:dump --yes --gzip --file=/var/www/html/.ddev/.downloads/db.sql.gz --project="${DDEV_PROVIDER_PROJECT_ID}" --environment="${DDEV_PROVIDER_ENVIRONMENT_NAME}"` which AFAIK gets the current running database. In testing I never did anything on platform.sh to create a "snapshot" or anything.

**Comment by andy-blum** [comment]
I was looking at the [flatfile yml](https://github.com/drud/ddev/pull/2763/files#diff-2b095badcbd08a6e628221e1176fb20656cc760dbd418cbe20d53db53fa449ed).

```
# This will pull a database and files from an existing location, for example,
# from a Dropbox location on disk
```

I also saw the rsync yml, but both of these look like they rely on db exports already existing rather than being able to take snapshots of the dev/test/live database on demand

**Comment by rfay** [comment]
You can do anything. The flatfile example uses an existing flatfile, for example, dropbox. But it's just a script. So for example, the platform one runs the platform cli tool inside the web container to pull down the database. There's also an rsync example. But it could do an ssh to do a dump before pulling the rsync.

**Pull request merged**
