### PR TITLE
Track and list stopped/removed projects, fixes #642

### LINKED ISSUE #642: Manage ddev project list independently of docker container labels (yaml)
## What happened (or feature request):

Over in https://github.com/drud/ddev/issues/484#issuecomment-363656446 the discussion is underway about ddev start/stop/rm, and one of the key reasons we've kept containers around (the "stopped" state) is just because ddev doesn't know what projects it has unless docker tells it. 

In reality we need to track projects separately from docker, because it's impossible for docker containers to represent the actual state of what a user may have set up. 

We've talked at times about using a ddev-managed yaml file in ~/.ddev to track project state; It would probably be more appropriate to use a real database like sqlite instead. Basically every start would put the key information into the db, and `ddev list` would report the info from that database (whether sqlite or yaml or whatever). Additional docker container information would be used to supplement the information about project state.

This allows us to:

* Fully catalog the projects that a user has created (and show their state)
* Fully prevent name collisions on projects
* Fully prevent databases accidentally being shared by projects.

Essentially, way back in the day (drud local days) docker containers were the easiest way to get info about projects, and we used it. But we've outgrown that, and it was inadequate always. It's time to leave it behind. 

I'd envision the following behavior:

* `ddev start` updates the database 
* `ddev stop` (our current "remove") also updates the db
* `ddev list` uses the database and supplements with live docker info to present its list. But it would know of all projects. It could *also* know the status of db (size, and whether it exists or has been removed, which can be pretty important and useful)
* Probably we'd need a new and completely separate `ddev rmdb` or something to trash the database, as database existence isn't really about start/stop/rm
* There would probably need to be a new command to remove projects from the list that the user didn't want to show any more, and probably `ddev list` would need some new filter options, for example to not show projects that have no database, or to not show projects that are inactive.

Destruction of the list db would be nonfatal (just deletion of a file) and the database could be recreated naturally just by starting projects.

This is most likely a prerequisite to #484 (reorganize stop/rm commands)

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)

3 - This appears relatively easy to implement, but will likely expose weaknesses in our code that will have to be dealt with.

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

Not all projects have been visible to `ddev list` and related commands. This is a longstanding issue and affects ddev-ui, but is more relevant now that `ddev stop` actually removes containers, effectively removing ddev's knowledge of the existence of the project.

## How this PR Solves The Problem:

* Add stopped projects (which have no containers) to global config, and query from there.

## TODO:

- [x] Sort projects by active and then by name
- [x] TestMain must not remove all projects, it needs to just remove projects like "Test*"
- [x] `ddev list` should probably show only active and paused projects. Add `ddev list --all` for the rest.
- [x] Need a new `ddev stop` flag that just stops and removes from global config, doesn't do everything else (nondestructive). Use that in cmd's root_test.go setup so it's not so dangerous.
- [x] Docs: 
    - Projects don't get added until they're started once
    - How to delete a project from global config

## Manual Testing Instructions:

* Test functionality with ddev-ui if it's still working
* `ddev stop -a` and `ddev list` and `ddev list --all` (which will show stopped/removed projects)
* Start a few projects and `ddev list`

There are so *very* many things that can be broken with this (starting/stopping/pausing by name, whether running or not, conflicting stuff in docker from what's in global config). Please spend some serious time poking at it, and trying to make sure you can recreate bugs.

## Automated Testing Overview:

- [x] Test for consistency between docker containers and global config project list
- [x] Test for behavior when global projectlist is not fully populated (as will be the case for lots of people)
- [ ] Test for situation where there are broken or empty projects in global config

## Related Issue Link(s):

OP #642 
This should also make ddev-ui work consistently assuming it gets revived.

### CODE REVIEW

**Comment by rfay** [comment]
@andrewfrench this is a biggie, requesting some serious look at this from both code and manual testing perspective. Since it changes the whole model from docker-label-query to global-yaml-projectlist, there's just so very much that can go wrong. Thanks for scheduling this in.

**Comment by ultimike** [comment]
I've been looking forward to this for awhile - I'm sure I've deleted a project's directory or two and forgetting to `ddev remove --remove-data` along the way.

I've been playing with the [alpha 1 version](https://twitter.com/randyfay/status/1133769670014586880) and so far, so good. I haven't run into any issues.

My only comment/request would be that the `ddev list --all` result be the default. With most folks using a standard `ddev start`/`ddev stop` workflow, using `ddev list` doesn't show anything different. I think it would be super-helpful to show stopped projects by default. Maybe include a `ddev list --no-stopped` switch or something like that...

-mike

**Comment by rfay** [comment]
Thanks @ultimike. I think that's a valid request, I thought it would be too big a list for people who work on a lot of projects. Maybe it should go the other way with a --active-only.

**Comment by rfay** [comment]
https://github.com/drud/ddev/pull/1636 will change the behavior to `ddev list` shows all projects, `ddev list --active-only` shows just active. Thanks!

**Pull request merged**
