### PR TITLE
Update github.com/google/go-github to v52

### PR DESCRIPTION
**Pull request by gilbertsoft**
## The Issue

The used package github.com/google/go-github is very outdated and must be updated.

## How This PR Solves The Issue

This PR updates the package and makes minor changes in the code because of some breaking changes.

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
My intent was that you just upgrade to current go-github. Please don't specify 52 in there. Maybe there's something I don't understand? Just using go-github should get you the right version, and it will be locked until we upgrade it again.

`go get -u github.com/google/go-github` - no changes to imports should be required.

**Comment by gilbertsoft** [comment]
> My intent was that you just upgrade to current go-github. Please don't specify 52 in there. Maybe there's something I don't understand? Just using go-github should get you the right version, and it will be locked until we upgrade it again.
> 
> `go get -u github.com/google/go-github` - no changes to imports should be required.

That does not work with the new modules feature of go see https://github.com/google/go-github#installation

**Comment by rfay** [comment]
This looks fine to me then and can be merged after `ddev get` and the version/update checking has been manually tested. Just let me know.

**Review by mattstein — APPROVED** [review]

**Comment by rfay** [comment]
I manually tested `ddev get --list` and update check in root.go, and both seemed right.

**Comment by gilbertsoft** [comment]
> OK, and I see the v52 is what they suggest.
> 
> Don't know what they could be saying about modules being enabled; we never used it any time in its history without modules enabled.

As far as I understand modules is a feature since 1.13 and enabled by default. But not all packages support it by default that's why some packages are requested without the versin suffix.

**Pull request merged**
