### PR TITLE
✨ bookmarklet support for Gitlabs & Bitbucket repos (corrected)

### PR DESCRIPTION
**Pull request by tyler36**
The Problem/Issue/Bug:
DDEV-gitpod bookmarklet does not support non-github "git repositories"

How this PR Solves The Problem:
This PR uses a regex expression to check for the 3 main repos

 Github - checks for "https://github.com"
 Gitlab - checks for "https://gitlab.com"
 Bitbucket - checks for "https://bitbucket."

This is an updated version of #3465 with improved Bitbucket resolution. 

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3526"></a>

### CODE REVIEW

**Comment by tyler36** [comment]
This PR improves on #3465 by correcting the bitbucket parsing.

The javascript code "translates" to 

```javascript
if(\/bitbucket\/.test(window.location.host) ) {
    paths=window.location.pathname.split("/")
    repo=[window.location.origin, paths[1], paths[2]].join("/")
}
if(/github.com|gitlab.com/.test(window.location.host)) {
    repo = window.location.href
}
if (repo) {
    window.location.href = "https://gitpod.io/#DDEV_REPO=" + encodeURIComponent(repo) + ",DDEV_ARTIFACTS=" + encodeURIComponent(repo) + "-artifacts/https://github.com/drud/ddev-gitpod-launcher/"
}
```

The following appear functionally equal.
- `git clone https://bitbucket.org/metadrop/drupal-8-search-api-solr-8/src/master/`
- `git clone https://bitbucket.org/metadrop/drupal-8-search-api-solr-8`

Informal polling suggests this is a "standard" format, atleast in-house. So the bitbucket part of the script grabs the first 2 items of the path, metadrop (username) & drupal-8-search-api-solr-8 (reponame) and uses this as the URL to send to ddev-gitpod. This also because the assumed artifact base (URL+'-artifacts').

**Comment by tyler36** [comment]
This solution has the benefit of leaving the URL handling up to end-users. Unlike https://github.com/drud/ddev-gitpod-launcher/pull/17 which was hard-coded based on assumptions.

If a user has a different URL pattern, they are free to create their own bookmarklet using whatever logic they require.

**Comment by tyler36** [comment]
The javascript was encoded using the following function:

```javascript
function fixedEncodeURIComponent(str) {
  return encodeURIComponent(str).replace(/[!'()*]/g, function(c) {
    return ' %' + c.charCodeAt(0).toString(16) + ' ';
  });
}
```

I'm not sure if there is a better way to generate it.

**Review by rfay — CHANGES_REQUESTED** [review]
I tried using this on the URL you suggested in the previous PR, https://bitbucket.csiro.au/users/bat161/repos/pytorch_unet/browse

But the result was 
> Checking out repository https://bitbucket.csiro.au/users/bat161
Attempting to get artifacts from https://bitbucket.csiro.au/users/bat161-artifacts
Cloning into '/tmp/bat161-artifacts'...
fatal: repository 'https://bitbucket.csiro.au/users/bat161-artifacts/' not found
Could not check out artifacts repo https://bitbucket.csiro.au/users/bat161-artifacts
Cloning into '/workspace/ddev-gitpod-launcher/bat161'...
fatal: repository 'https://bitbucket.csiro.au/users/bat161/' not found

**Comment by rfay** [comment]
I went ahead and rebased this, so make sure you do a `git fetch` and `git reset --hard <remote>/tyler36/2020_01_17_fix_bitbucket_gitpod_bookmarklet` or whatever.

**Review by rfay — CHANGES_REQUESTED** [review]
My experience remains the same:

```
Checking out repository https://bitbucket.csiro.au/users/bat161
Attempting to get artifacts from https://bitbucket.csiro.au/users/bat161-artifacts
Cloning into '/tmp/bat161-artifacts'...
fatal: repository 'https://bitbucket.csiro.au/users/bat161-artifacts/' not found
Could not check out artifacts repo https://bitbucket.csiro.au/users/bat161-artifacts
Cloning into '/workspace/ddev-gitpod-launcher/bat161'...
fatal: repository 'https://bitbucket.csiro.au/users/bat161/' not found
```

I still don't think it's all that important to do bitbucket if you want to just skip it.

**Comment by tyler36** [comment]
I did a bit more search and "https://bitbucket.csiro.au/users/bat161/repos/pytorch_unet/browse" appear to be non-standard format. I don't think we will get this one working 

A more common format is the following (which _should_ work with this PR)

- https://bitbucket.org/metadrop/drupal-8-search-api-solr-8/src/master/
- https://bitbucket.org/websolutionshr/drupal-8-ws-starterkit/src/master/

Either way, this PR is better than the original since it adds Gitlab support (and potential bitbucket). If we get a lot of bitbucket issues / discord threads, we will have real-world URLs that will help tweak it.

Happy to see it merged.

**Comment by rfay** [comment]
On a road trip with my wife so will look at this more closely later, thanks so much!

**Comment by rfay** [comment]
https://bitbucket.org/metadrop/drupal-8-search-api-solr-8/src/master/ mostly worked for me. Out of date composer stuff, but that's not this bookmarklet's responsibility!

Thanks so much for the long, hard pull on this one. It's such a great contribution.

**Pull request merged**
