### PR TITLE
.git needs to be synced for Composer self.version

### PR DESCRIPTION
**Pull request by deviantintegral**
## The Problem/Issue/Bug:

I ran into issues trying to run `ddev composer require drush/drush` on a Drupal 9 checkout. Syncing the `.git` directory fixed it, allowing composer to properly resolve version contraints.

## How this PR Solves The Problem:

Updates the docs to call this situation out.

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3398"></a>

### CODE REVIEW

**Comment by rfay** [comment]
Thanks, this is a good addition. See also https://github.com/drud/ddev/issues/3384

I excluded .git by default in mutagen.yml because the maintainer of mutagen was concerned that the low-level (and so-many-files) filesystem usage of .git could lead to trouble.

**Comment by rfay** [comment]
It's interesting, the two places where this has been a problem, git most likely won't be used, and certainly won't be used in the container, but it breaks composer. Is this a composer flaw in the end I wonder? I wonder how we can avoid people having to discover this over and over. (Docs are good, but mostly people don't read them.)

**Comment by deviantintegral** [comment]
> I excluded .git by default in mutagen.yml because the maintainer of mutagen was concerned that the low-level (and so-many-files) filesystem usage of .git could lead to trouble.

That's really interesting. Given default Drupal 9 has ~25K files in in `core` and `vendor`, it doesn't seem like there would be an order of magnitude difference compared to the operations Composer or npm makes. Actually, npm as well would usually dwarf a .git directory.

> I wonder how we can avoid people having to discover this over and over. (Docs are good, but mostly people don't read them.)

We could test for `self.version` in `composer.json`?

**Comment by rfay** [comment]
I have an idea: We should just bind-mount .git, it would solve so many things. Use the technique in https://ddev.readthedocs.io/en/latest/users/performance/#advanced-mutagen-configuration-options - but do it automatically.

**Comment by rfay** [comment]
Opened 
* https://github.com/drud/ddev/issues/3400

**Review by rfay — APPROVED** [review]
I hope to add .git and upload_dir direct mounting in a release soon, but will go ahead and do this now and it can be edited with that PR.

**Comment by rfay** [comment]
Thanks so much for this!

**Pull request merged**
