### PR TITLE
Fix issue where the script doesn't fire on page load or search.

### PR DESCRIPTION
**Pull request by mikesnoeren**
## The Problem/Issue/Bug:
This PR fixes part of [this issue](https://github.com/drud/ddev/issues/4059) by triggering the `fixTabs` function on page load and on hash change.

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4069"></a>

## Manual testing
Use [this link](https://ddev--4069.org.readthedocs.build/en/latest/users/install/ddev-installation/#linux) to test, you'll notice the page automatically opening the Linux tab.

### CODE REVIEW

**Comment by rfay** [comment]
Thanks for working on this @mikesnoeren ! Please keep working on it!

If I go to https://ddev--4069.org.readthedocs.build/en/4069/users/install/docker-installation/#linux on a browser that's setting on the front page... It just lands on https://ddev--4069.org.readthedocs.build/en/4069/users/install/docker-installation, the base page, not on the tab. 

However, I see that if I go to https://ddev--4069.org.readthedocs.build/en/4069/users/install/ddev-installation/#windows-wsl2 it does great AND it highlights the Windows WSL2 tab. So I think it's going to work, we just have some miles to walk yet. 

Thanks!

**Comment by mikesnoeren** [comment]
> If I go to https://ddev--4069.org.readthedocs.build/en/4069/users/install/docker-installation/#linux on a browser that's setting on the front page... It just lands on https://ddev--4069.org.readthedocs.build/en/4069/users/install/docker-installation, the base page, not on the tab.

I'm sorry but I can't reproduce that, everything works fine for me.
Could you give me the exact steps to reproduce the issue and the name and version of your browser?

**Comment by rfay** [comment]
Works for me in incognito also.

**Comment by rfay** [comment]
Test plan:

For each test, make sure to be on the base page, https://ddev--4069.org.readthedocs.build/en/4069

- [ ] Search for "steps". First hit is "Linux", "don't forget docker-ce post-install steps".  Click it, you should get to that content. URL is https://ddev--4069.org.readthedocs.build/en/4069/users/install/docker-installation/#linux
- [ ] Search for chocolatey. Second hit is "Docker Desktop for Windows". Click it, you should get to that content, URL is https://ddev--4069.org.readthedocs.build/en/4069/users/install/docker-installation/#docker-desktop-for-windows
- [ ] Search for gitpod. First hit is gitpod.io. Hit it, URL is https://ddev--4069.org.readthedocs.build/en/4069/users/install/ddev-installation/#gitpodio - you should get to the gitpod dont-have-to-install page.
- [ ] Search for groupadd. Only hit is linux docker install, https://ddev--4069.org.readthedocs.build/en/4069/users/install/docker-installation/#linux - link should take you to linux tab
- [ ] Search for apt. Only hit is linux ddev install, https://ddev--4069.org.readthedocs.build/en/4069/users/install/ddev-installation/#apt-packages-for-debian-based-systems - Should get the linux tab (didn't work for me)

For each test, open a new tab.
- [ ] Visit https://ddev--4069.org.readthedocs.build/en/4069/users/install/docker-installation/#linux - you should get the linux tab. 
- [ ] Visit https://ddev--4069.org.readthedocs.build/en/4069/users/install/docker-installation/#docker-desktop-for-windows - you should get docker desktop tab
- [ ] https://ddev--4069.org.readthedocs.build/en/4069/users/install/ddev-installation/#gitpodio - should get to gitpod tab
- [ ] https://ddev--4069.org.readthedocs.build/en/4069/users/install/docker-installation/#linux - should get to linux install tab
- [ ] https://ddev--4069.org.readthedocs.build/en/4069/users/install/ddev-installation/#apt-packages-for-debian-based-systems - should get to linux tab

**Comment by rfay** [comment]
I just tried the first item (macOS, Chrome, incognito) a few times and it failed each time. Searched for steps, got the URL https://ddev--4069.org.readthedocs.build/en/4069/users/install/docker-installation/#linux, it landed on the macOS tab.

**Comment by mikesnoeren** [comment]
I disabled the `navigation.instant` feature for `mkdocs-material` which caused the page to act like a SPA. 
This should fix the issues above as the docs now do an actual redirect instead of content injection when using search results..

If the `navigation.instant` feature is required by someone I can probably get it to work, but as all of my earlier fixes are temporarily this seemed like the best option for now.

**Comment by rfay** [comment]
Thanks, I'll give it a go!

**Comment by rfay** [comment]
Thanks so much, absolutely awesome!

**Comment by rfay** [comment]
Thanks so much for solving this!

**Pull request merged**
