### PR TITLE
Make TYPO3 work with mailhog

### PR DESCRIPTION
**Pull request by spoonerWeb**
## The Problem/Issue/Bug:
Wrong sendmail command to send mails in TYPO3 environment

## How this PR Solves The Problem:
Add the missing parameter

## Manual Testing Instructions:
See #924 

## Automated Testing Overview:
There are no tests for this, are they?

## Related Issue Link(s):
#924 

## Release/Deployment notes:
Not afaik

### CODE REVIEW

**Comment by rickmanelius** [comment]
If the tests pass, I say we pull this in.

**Comment by rfay** [comment]
This needs to be linked to mailhog documentation that confirms the usage before it can be pulled. The previous usage was correct for years and years, so I assume that something has shifted in mailhog.

**Comment by rfay** [comment]
I don't think we need to get this into v0.20.0, and there hasn't been any followup, but I'm pretty sure the appropriate fix is to set `transport => 'mail' ` in the AdditionalSettings.php. For TYPO3 users the immediate approach is just to set the transport in TYPO3 settings

**Comment by rfay** [comment]
I think the path forward is to open another PR that does:

* transport => 'mail'
* `SYS/displayErrors => 1`
*  `SYS/devIPmask => '*'

**Comment by psychomieze** [comment]
Especially if we want to make this compatible with as many systems (read: Windows) as possible, we should probably switch to the following configuration for TYPO3 (and not touch the php.ini files at all):

```
    'MAIL' => [
        'transport' => 'smtp',
        'transport_smtp_server' => 'localhost:32769',
    ],
```
with the host and port of the mailhog container. This should be the most reliable option.

**Comment by rfay** [comment]
Just to be clear: None of this is related to or even has anything to do with WIndows. This all happens inside the web container, which is Debian Linux. If we were going to use SMTP, the mailhog smtp port is port 1025, and if that seems better to you, we could probably do it. But then any change to the mailhog config would break TYPO3 projects. As it is, the configuration is encapsulated in sendmail_path so it should work for any CMS that is using mail()

**Comment by rfay** [comment]
Very thoughtful response from @jigal in [slack](https://typo3.slack.com/archives/C8TRNQ601/p1530002562000405):

> I did some digging in mail handling in PHP and how we can use this in TYPO3.
TYPO3 uses SwiftMailer to send emails. SwiftMailer has deprecated the use of the PHP `mail()` function as mail transport and can remove support completely at any moment. Therefore we have to switch to either "sendmail" or "SMTP".
According to the PHP documentation `mail()` uses either sendmail (or something compatible) or SMTP (only on Windows and only if `sendmail_path` is empty). This is configured in the php.ini settings. 
> TYPO3 can use the php.ini settings (at least for new installations) to configure the mail settings as most installations have a working `mail()` function. If sendmail_path is empty (and SMTP is empty on Windows) we can only ask the user how installs TYPO3.
So, please don't rely on the 'mail' transport, but make sure the php.ini setting `sendmail_path` can be copied to the TYPO3 mail settings and SwiftMailer can use that command. If someone prefers to use SMTP they can configure this themselves IMO.

**Comment by rfay** [comment]
Thanks so much for bringing this to the fore and taking the initiative to do a PR @spoonerWeb - Per the discussion here, the php.ini technique is not what's needed, so I'm going to close this one out. I think the key info is in https://github.com/drud/ddev/issues/924, and I hope to get that into the next release. A followup PR from you is welcome if you want, probably best setting the transport to SMTP and port 25 in the AdditionalSettings.php

**Pull request closed without merging**
