### PR TITLE
Persist data after container removal with named MySQL volumes

### PR DESCRIPTION
**Pull request by beeradb**
## The Problem:
This was merged in #340 and then reverted in #347 due to failing the nightly master build. Other tests work fine. We need to track down the failure and re-merge it once we've found the source of the problem.

### CODE REVIEW

**Comment by rfay** [comment]
It's easy to run the nightly build against this branch on your fork, which allows easier iteration on debugging.

1. Enable circleci on your beeradb/ddev fork (add project at https://circleci.com/projects/gh/beeradb)
2. Get Circle token for beeradb/ddev at Settings->Api Permissions 
3. Trigger with:
```
.circle_ci/trigger_build.sh <beeradb ddev circle token> beeradb/ddev named-volumes 
```

Then... Don't remember to turn off circle integration on your branch after you have it solved, or you'll be baffled why the builds aren't happening on your PR.

Happy to help any way I can.

**Comment by rfay** [comment]
So this just doesn't work on linux as far as I can tell. I'm not sure how it would have worked in PR build earlier, unless we're missing a test somehow.

The test failure is:
```
--- FAIL: TestLocalLogs (0.01s)
	Error Trace:	local_test.go:360
	Error:		"" does not contain "Database initialized"
		

	Error Trace:	local_test.go:366
	Error:		"" does not contain "MySQL init process done. Ready for start up."
```

On linux, with docker 17.05, I built this branch, then started a plain d7 site.

ddev list shows unhealthy:
```
NAME      TYPE     LOCATION    URL                         STATUS
randyfay  drupal7  ~/randyfay  http://randyfay.ddev.local  db service unhealthy
```

and ddev logs shows the problem we're seeing that I believe results in the test failure, "Corrupted prefix" and no "MySQL init process done":

```
$ ddev logs -s db
DEBU[0000] Finished config read                          Read config={
  APIVersion: "1",
  Name: "randyfay",
  AppType: "drupal7",
  Docroot: "",
  WebImage: "drud/nginx-php-fpm7-local:v0.7.3",
  DBImage: "drud/mysql-local-57:v0.5.0",
  DBAImage: "drud/phpmyadmin:v0.2.0",
  ConfigPath: "/home/rfay/randyfay/.ddev/config.yaml",
  AppRoot: "/home/rfay/randyfay",
  Platform: "local",
  SiteSettingsPath: ""
}
DEBU[0000] Finished config set                           Active config={
  APIVersion: "1",
  Name: "randyfay",
  AppType: "drupal7",
  Docroot: "",
  WebImage: "drud/nginx-php-fpm7-local:v0.7.3",
  DBImage: "drud/mysql-local-57:v0.5.0",
  DBAImage: "drud/phpmyadmin:v0.2.0",
  ConfigPath: "/home/rfay/randyfay/.ddev/config.yaml",
  AppRoot: "/home/rfay/randyfay",
  Platform: "local",
  SiteSettingsPath: "/home/rfay/randyfay/sites/default/settings.php"
}
DEBU[0000] Corrupted prefix: []
```

**Comment by tannerjfco** [comment]
I am able to reproduce the test failure on macOS with the following conditions (I've only been able to repro in test run, unable to repro from manual testing):

- Create a fresh build of the mysql container locally.
- On this branch, Change mysql tag in Makefile to the container tag you built.
- Run `make testpkg`

**Comment by rfay** [comment]
@tannerjfco pointed me to https://github.com/docker-library/mysql/issues/255#issuecomment-310760881, which is what got him onto the VOLUME removal kick. You'll note in the OP there that they're talking about some significant disadvantages with using a volume instead of a mount.  Apparently
* No garbage collection, so disk usage grows extraordinarily?
* Normal? situation would be to host mount for mysql?
* Difficulty of figuring out how to remove the volume?

**Comment by rfay** [comment]
After rereading the [docker volume docs](https://docs.docker.com/engine/tutorials/dockervolumes/#important-tips-on-using-shared-volumes) I'm not sure that we actually get a win out of this approach. Instead of mounting the database into a known location where it can be easily managed/deleted or even backed up, it's hidden in a docker location on the host (managed by `docker volume`), but the actual technology seems to be exactly the same - the container mounts the directory from the host. It's just that with this approach, the host location is magically hidden and managed by docker.

**Comment by rfay** [comment]
So there may be more than one problem here that we're conflating.
1. mysql startup failure in some cases (demonstrated in TestLocalLogs and `ddev logs -s db` by no db-ready statement (I can't recreate this on macos although Tanner has done it. I have seen it perniciously on linux, but then was unable to recreate in a clear way)
2. `DEBU[0000] Corrupted prefix: []` statement from `ddev logs -s db`. This is easily recreatable on osx and linux. It probably needs to be debugged. It may or may not be important, but it looks ugly. I mean CORRUPTED.

**Comment by rickmanelius** [comment]
Hi @rfay. Two factors that I liked about this approach were 1) we get some business logic and functionality for free without having to maintain a parallel approach and 2) abstracting/moving the files into a location that wouldn't get destroyed if someone removed the repo. Technically we could still address item 2 by moving the storage to ~/.ddev and then it comes down to the perceived benefits listed in item 1.

**Comment by rickmanelius** [comment]
BTW. I haven't caught up to the entire thread. I was merely responding to https://github.com/drud/ddev/pull/349#issuecomment-311362248. After another scan, it looks like there might be some other considerations between volumes and a mount that we specify/control.

**Comment by tannerjfco** [comment]
I was finally able to pin down this issue. Named docker volumes were not being fully cleaned up as expected after test runs. I was able to determine this by adding "docker volume list" and "docker volume prune -f" before the test runs. The nightly build ends up running the tests 3 times, and since the volumes were persisting between runs, the next run would end up starting a site with the previous run's volume, which results in the db container providing no log output.

The area specifically where cleanup wasn't occurring was the Cleanup() function for 'manually' removing a site if no compose file is present. While the container removal code specifies to remove the associated volume when the container is removed, this doesn't appear to be working as expected. Expanding the cleanup function to remove volumes looks to resolve the issue.

**Comment by beeradb** [comment]
A metaphor for this PR: https://media.giphy.com/media/l0IxYWDltdHEqujnO/giphy.gif

We've decided to go with host mounting for volumes. The most compelling reason we did this was that we're always willing to bet against docker stability, and we'd like to maintain the ability for people to reset their local docker setup if needed. We'll still persist data to the host via #337

**Pull request closed without merging**
