### PR TITLE
remove data after containers down so removal succeeds in windows

### PR DESCRIPTION
**Pull request by tannerjfco**
## The Problem:
The current approach for removing data on `ddev rm --remove-data` is to remove the data directories, then bring down the containers. This works ok on Mac and Linux, but Windows won't remove mysql bin data mount or its contents while the containers are running. 

## The Fix:
This changes the order of operations so that data removal happens after the containers are removed. This allows the directories to be successfully removed on Windows.

## The Test:
On a windows machine, start up a ddev site, and import a database. Then, run `ddev rm --remove-data`. Prior to this fix, the command would immediately fail on removing the data directories. With this fix, the containers should come down first, and then data removal should succeed as expected.

## Automation Overview:

I don't believe there's a relevant automation change at this time since this issue only surfaced on Windows, which our automation doesn't currently handle.

### CODE REVIEW

**Comment by rfay** [comment]
Hmm, thought I'd already fixed this. Maybe I lost it along the way. It may be in the windows PR.

**Comment by rfay** [comment]
Yeah, think it's in https://github.com/drud/ddev/pull/387/commits/ba4d77ac51e7c4c99f4b0f0827b970d0771d2f0a in https://github.com/drud/ddev/pull/387 - I'm OK with it going in here and I'll rebase.

**Comment by tannerjfco** [comment]
d'oh! I stumbled on the issue while testing Pantheon and figured I should do a quick fix. I forgot there were some non-test fixes in #387. I'm not blocked by this issue, so I'm fine with the fix coming in either way. It's probably easier to roll with what Randy has in his PR

**Comment by tannerjfco** [comment]
Closing since this is addressed in #387

**Pull request closed without merging**
