### PR TITLE
Fixes DDev WordPress Config Files for Override & Coding Standards, fixes #2795

### LINKED ISSUE #2795: WordPress config file overwrites some settings it probably shouldn't
**Describe the bug**

WordPress has the lovely behavior of hard-coding links, so when pulling a live site for local dev, one needs to update the hostname somehow.  What I usually do is set the WP_HOME and WP_SITEURL constants in my wp-config.php file, and use `local.example.com`.

Currently, wp-config-ddev.php is setting WP_HOME itself, in a way that overwrites anything that might already be there. It should probably be wrapped in `if (defined('WP_HOME'))` to avoid this problem.  That way I can use whichever version I like.

I also wonder why the table prefix is set in ddev's config file.  It's the same as what comes in the default wp-config.php, so if I've changed it in the main wp-config, I have to either manage the ddev settings myself (remove the autogenerated comment), or add another layer of settings (wp-config-local.php) as I would with a Drupal project.  I'm not opposed to doing the latter, I just don't understand why it's there, since it's the same as the default.

**To Reproduce**

- Configure a project with `local.example.com` in the additional_fqdns.
- ddev start
- Try to load `local.example.com` and see that you get redirected or other undesired behavior

**Expected behavior**

Leave my HOME setting along if it exists, and preferably don't reset the db prefix.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Catalina
- Docker Desktop version: 2.5.0.1
- ddev version information: v1.17.0-alpha3
- config.yaml contents for the misbehaving project
```
name: example-site
type: wordpress
docroot: ""
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
  - local.example.com
mariadb_version: "10.3"
mysql_version: ""
provider: default
use_dns_when_possible: true
composer_version: ""
web_environment: []
```

**Additional context**

Here's an example wp-config.php:

```
<?php

define('WP_HTTP_HOST', 'http://local.example.com');

define( 'DISALLOW_FILE_EDIT', true );
define( 'WP_POST_REVISIONS', 10 );
define( 'AUTOSAVE_INTERVAL', 180 ); // Seconds

define( 'WP_CONTENT_DIR', dirname(__FILE__) . '/content' );
define( 'WP_CONTENT_URL', WP_HTTP_HOST . '/content' );
define( 'UPLOADS', 'files' );
define('WP_HOME', WP_HTTP_HOST);
define('WP_SITEURL', WP_HTTP_HOST);

// define( 'FORCE_SSL_LOGIN', true );
// define( 'FORCE_SSL_ADMIN', true );

//define( 'DB_NAME', 'example' );
//define( 'DB_USER', 'root' );
//define( 'DB_PASSWORD', 'root' );
//define( 'DB_HOST', '127.0.0.1' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

$table_prefix = 'exp_';

define( 'WP_DEBUG', false );

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

// Include for ddev-managed settings in wp-config-ddev.php.
$ddev_settings = dirname(__FILE__) . '/wp-config-ddev.php';
if (is_readable($ddev_settings) && !defined('DB_USER')) {
	require_once($ddev_settings);
}

require_once ABSPATH . 'wp-settings.php';
```

I can submit a PR for this to help speed it along, just want to make sure the need is understood and desirable for a fix.

### PR DESCRIPTION
**Pull request by timnolte**
## The Problem/Issue/Bug:

Currently, the generated `wp-config-ddev.php` defines the following WordPress configuration constants without checking if they are already defined:

* `DB_NAME`
* `DB_USER`
* `DB_PASSWORD`
* `DB_HOST`
* `WP_HOME`
* `WP_SITEURL`
* `WP_DEBUG`

Additionally, the `$table_prefix` global variable is set such that it will override any changes if the DDev configuration is included first which can prevent operability with configurations that have intentionally changed the WordPress table prefix. This setup become problematic with heavily customized WordPress setups and those that use, for example, the dotenv package to manage the WordPress configuration depending on the running environment.

## How this PR Solves The Problem:

* Changes `wp-config-ddev.php` output to allow overriding when included in an existing WordPress project configuration.
* Updates both the `wp-config.php` and `wp-config-ddev.php` output to follow WordPress coding standards.

## Manual Testing Instructions:

To test this PR, go to [checks](https://github.com/drud/ddev/pull/3468/checks) and choose "PR Build" and all the downloads will be there.  You can also test general functionality on [gitpod](https://gitpod.io/#https://github.com/drud/ddev/pull/3468)

1. Checkout or setup a new WordPress project.
2. Add the `// Include for ddev-managed settings in wp-config-ddev.php.` snippet along with the `wp-config-ddev.php` include code to a custom `wp-config.php` with any of the listed constants defined, or a custom `$table_prefix` defined.
3. Once started the site should be using the predefined constants in favor of the DDev generated values.

## Automated Testing Overview:

N/A

## Related Issue Link(s):

Fixes #2795

## Release/Deployment notes:

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3468"></a>

### CODE REVIEW

**Comment by rfay** [comment]
I took the liberty of moving the two PHP templates for wordpress into separate files. This was hard to do until recent versions of golang, but now it's easy, and it will make it loads easier for you to maintain this. Now you can take a look and fiddle with them as regular PHP files in your favorite IDE and make sure they're formatted the way you want, etc.

**Comment by timnolte** [comment]
@rfay ah, yeah, that makes it way easier. I resorted to putting things in a PHP file in a project of mine that had WordPress coding standards linting checks and automatic fixer so that I could format things properly. Then I copied it back into the Go files.

**Comment by rfay** [comment]
Yeah, when you get a chance feel free to check those again. In the WP world are 4 spaces usual for a tab?

**Comment by rfay** [comment]
I see that the [WordPress coding standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/) do actually use tabs. I thought all the PHP projects had gone away from tabs, but I was obviously wrong. (One of the great things about golang is that there are no choices to be made about these things. Tabs are required, and there's an official gofmt that basically enforces (and reformats) your code so none of the things people fight about in the PHP world are relevant.)

**Comment by timnolte** [comment]
@rfay I rebased my branch with `master` in order to keep this work up-to-date and ready to be merged in. I also added EditorConfig & PHP CodeSniffer configuration files to the `pkg/ddevapp/wordpress` directory in order to assist with maintaining those files. Can you approve the builds on this PR so that I can test one more time?

**Comment by rfay** [comment]
I approved the test runs, but github is having some trouble, so don't be surprised if they don't go green.

**Comment by rfay** [comment]
You'll still have to copy those bundled files from the embedded filesystem to where you want them to go (project root?) using something like https://github.com/drud/ddev/blob/7b0e3a064edab2c5dfce39fa535eab11d0c12465/pkg/ddevapp/assets.go#L27

But is it legit to throw something into people's project?

**Comment by timnolte** [comment]
@rfay you last mention about copying files was that in reference to the `phpcs.xml.dist` & `.editorconfig` files I added? If so my intention wasn't that these files would be dropped into projects by DDev, this is only for ongoing development of those config file templates.

**Comment by rfay** [comment]
Oh, that's nice then! Thanks! I like it.

**Comment by timnolte** [comment]
Tested the latest PR build and things are working as expected. I had a couple of other people download and test the PR binaries on macOS as well and they also reported no issues.

**Comment by rfay** [comment]
Outstanding, nice work on this. Thanks!

**Comment by timnolte** [comment]
@rfay is it possible to get a 1.18.3-beta release out there so that we can easily point to a release to download that has these fixes? Do you have any thoughts on when the 1.18.3 release might happen? Thanks!

**Comment by rfay** [comment]
If you're using homebrew, `brew install --HEAD ddev`. 

Otherwise, if the pressure is on I'll do a prerelease soon :)

Thanks for the great work on this.

**Comment by rfay** [comment]
My plan is to finish up the PRs that are in flight and then do an edge-channel release. Could be this week, but I'd expect certainly by next week.

**Comment by rfay** [comment]
This is included in v1.19.0-alpha1, https://github.com/drud/ddev/releases/tag/v1.19.0-alpha1

**Pull request merged**
