### PR TITLE
Escape composer versions in docs so they work in Windows cmd

### PR DESCRIPTION
**Pull request by gilbertsoft**
## The Problem/Issue/Bug:
`  [InvalidArgumentException]
  Could not find package typo3/cms-base-distribution with version 9.`

### CODE REVIEW

**Comment by rfay** [comment]
Hmm, the ^9 still comes directly from https://composer.typo3.org/

And I still had no trouble with it at all, maybe you can explain the actual problem. Was this perhaps a temporary issue with upstream packaging?

```
$ ddev composer create typo3/cms-base-distribution ^9 --no-interaction --prefer-dist
Building ddev-ssh-agent
Recreating ddev-ssh-agent ... done

ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Building db
Building web
Creating ddev-junk-db ... done
Creating ddev-junk-web ... done
Creating ddev-junk-dba ... done

Recreating ddev-router ... done

Warning: ALL EXISTING CONTENT of the project root (/Users/rfay/workspace/junk) will be deleted
Would you like to continue? [Y/n] (yes):
Removing any existing files in project root
Executing composer command: composer create-project typo3/cms-base-distribution /var/www/html/.tmp_ddev_composer_create_wBBKTv ^9 --no-interaction --prefer-dist

Installing typo3/cms-base-distribution (v9.5.0)
  - Installing typo3/cms-base-distribution (v9.5.0): Loading from cache
Created project in /var/www/html/.tmp_ddev_composer_create_wBBKTv
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 74 installs, 0 updates, 0 removals
  - Installing typo3/cms-composer-installers (v2.2.2): Loading from cache
  - Installing typo3/class-alias-loader (1.0.1): Loading from cache
  - Installing helhum/typo3-console-plugin (v2.0.5): Loading from cache
  - Installing typo3fluid/fluid (2.6.2): Downloading (100%)
  - Installing typo3/phar-stream-wrapper (v3.1.2): Loading from cache
  - Installing typo3/cms-cli (2.0.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.12.0): Loading from cache
  - Installing symfony/yaml (v4.3.4): Downloading (100%)
  - Installing symfony/routing (v4.3.4): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.12.0): Loading from cache
  - Installing symfony/polyfill-php72 (v1.12.0): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.12.0): Loading from cache
  - Installing symfony/intl (v4.3.4): Downloading (100%)
  - Installing symfony/polyfill-intl-icu (v1.12.0): Loading from cache
  - Installing symfony/finder (v4.3.4): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/service-contracts (v1.1.6): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/var-exporter (v4.3.4): Downloading (100%)
  - Installing symfony/cache-contracts (v1.1.5): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/cache (v4.3.4): Downloading (100%)
  - Installing symfony/expression-language (v4.3.4):Downloading (100%)         )
  - Installing symfony/polyfill-php73 (v1.12.0): Loading from cache
  - Installing symfony/console (v4.3.4): Downloading (100%)
  - Installing swiftmailer/swiftmailer (v5.4.12): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing psr/http-server-handler (1.0.1): Loading from cache
  - Installing psr/http-server-middleware (1.0.1): Loading from cache
  - Installing nikic/php-parser (v4.2.4): Downloading (100%)
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing doctrine/lexer (1.1.0): Loading from cache
  - Installing doctrine/instantiator (1.2.0): Loading from cache
  - Installing doctrine/event-manager (v1.0.0): Loading from cache
  - Installing doctrine/cache (v1.8.0): Loading from cache
  - Installing doctrine/dbal (v2.9.2): Loading from cache
  - Installing doctrine/annotations (v1.7.0): Loading from cache
  - Installing cogpowered/finediff (0.3.1): Loading from cache
  - Installing algo26-matthias/idna-convert (v1.1.0): Loading from cache
  - Installing typo3/cms-core (v9.5.9): Loading from cache
  - Installing typo3/cms-recordlist (v9.5.9): Loading from cache
  - Installing typo3/cms-extbase (v9.5.9): Loading from cache
  - Installing typo3/cms-fluid (v9.5.9): Loading from cache
  - Installing typo3/cms-install (v9.5.9): Loading from cache
  - Installing typo3/cms-frontend (v9.5.9): Loading from cache
  - Installing typo3/cms-filelist (v9.5.9): Loading from cache
  - Installing typo3/cms-extensionmanager (v9.5.9): Loading from cache
  - Installing typo3/cms-backend (v9.5.9): Loading from cache
  - Installing typo3/minimal (v9.5.0)
  - Installing helhum/config-loader (v0.12.2): Loading from cache
  - Installing symfony/process (v4.3.4): Downloading (100%)
  - Installing typo3/cms-scheduler (v9.5.9): Loading from cache
  - Installing helhum/typo3-console (v5.7.2): Loading from cache
  - Installing typo3/cms-about (v9.5.9): Loading from cache
  - Installing typo3/cms-viewpage (v9.5.9): Loading from cache
  - Installing typo3/cms-tstemplate (v9.5.9): Loading from cache
  - Installing typo3/cms-t3editor (v9.5.9): Loading from cache
  - Installing typo3/cms-sys-note (v9.5.9): Loading from cache
  - Installing typo3/cms-seo (v9.5.9): Loading from cache
  - Installing typo3/cms-setup (v9.5.9): Loading from cache
  - Installing typo3/cms-rte-ckeditor (v9.5.9): Loading from cache
  - Installing typo3/cms-reports (v9.5.9): Loading from cache
  - Installing typo3/cms-redirects (v9.5.9): Loading from cache
  - Installing typo3/cms-info (v9.5.9): Loading from cache
  - Installing typo3/cms-impexp (v9.5.9): Loading from cache
  - Installing typo3/cms-form (v9.5.9): Loading from cache
  - Installing typo3/cms-fluid-styled-content (v9.5.9): Loading from cache
  - Installing typo3/cms-felogin (v9.5.9): Loading from cache
  - Installing typo3/cms-beuser (v9.5.9): Loading from cache
  - Installing typo3/cms-belog (v9.5.9): Loading from cache
  - Installing typo3/cms-adminpanel (v9.5.9): Loading from cache
symfony/routing suggests installing symfony/http-foundation (For using a Symfony Request object)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/service-contracts suggests installing symfony/service-implementation
symfony/console suggests installing symfony/event-dispatcher
symfony/console suggests installing symfony/lock
guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
helhum/config-loader suggests installing ext-yaml (For improved performance when parsing yaml files you should use the PECL YAML Parser php extension)
Writing lock file
Generating autoload files
> typo3cms install:fixfolderstructure
> typo3cms install:generatepackagestates
Generating class alias map file
Inserting class alias loader into main autoload.php file
The following directory structure has been fixed:
Directory /typo3temp successfully created.
Fixed permission on /typo3temp.
File /typo3temp/index.html successfully created.
Set content to /typo3temp/index.html
Fixed permission on /typo3temp/index.html.
Directory /typo3temp/assets successfully created.
Fixed permission on /typo3temp/assets.
Directory /typo3temp/assets/compressed successfully created.
Fixed permission on /typo3temp/assets/compressed.
Directory /typo3temp/assets/css successfully created.
Fixed permission on /typo3temp/assets/css.
Directory /typo3temp/assets/js successfully created.
Fixed permission on /typo3temp/assets/js.
Directory /typo3temp/assets/images successfully created.
Fixed permission on /typo3temp/assets/images.
Directory /typo3temp/assets/_processed_ successfully created.
Fixed permission on /typo3temp/assets/_processed_.
Directory /typo3temp/var successfully created.
Fixed permission on /typo3temp/var.
File /typo3temp/var/.htaccess successfully created.
Set content to /typo3temp/var/.htaccess
Fixed permission on /typo3temp/var/.htaccess.
Directory /typo3temp/var/charset successfully created.
Fixed permission on /typo3temp/var/charset.
Directory /typo3temp/var/cache successfully created.
Fixed permission on /typo3temp/var/cache.
Directory /typo3temp/var/lock successfully created.
Fixed permission on /typo3temp/var/lock.
Directory /typo3conf successfully created.
Fixed permission on /typo3conf.
Directory /typo3conf/ext successfully created.
Fixed permission on /typo3conf/ext.
Directory /typo3conf/l10n successfully created.
Fixed permission on /typo3conf/l10n.
Directory /fileadmin successfully created.
Fixed permission on /fileadmin.
Directory /fileadmin/_temp_ successfully created.
Fixed permission on /fileadmin/_temp_.
File /fileadmin/_temp_/.htaccess successfully created.
Set content to /fileadmin/_temp_/.htaccess
Fixed permission on /fileadmin/_temp_/.htaccess.
File /fileadmin/_temp_/index.html successfully created.
Set content to /fileadmin/_temp_/index.html
Fixed permission on /fileadmin/_temp_/index.html.
Directory /fileadmin/user_upload successfully created.
Fixed permission on /fileadmin/user_upload.
Directory /fileadmin/user_upload/_temp_ successfully created.
Fixed permission on /fileadmin/user_upload/_temp_.
File /fileadmin/user_upload/_temp_/index.html successfully created.
Set content to /fileadmin/user_upload/_temp_/index.html
Fixed permission on /fileadmin/user_upload/_temp_/index.html.
Directory /fileadmin/user_upload/_temp_/importexport successfully created.
Fixed permission on /fileadmin/user_upload/_temp_/importexport.
File /fileadmin/user_upload/_temp_/importexport/.htaccess successfully created.
Set content to /fileadmin/user_upload/_temp_/importexport/.htaccess
Fixed permission on /fileadmin/user_upload/_temp_/importexport/.htaccess.
File /fileadmin/user_upload/_temp_/importexport/index.html successfully created.
Set content to /fileadmin/user_upload/_temp_/importexport/index.html
Fixed permission on /fileadmin/user_upload/_temp_/importexport/index.html.
File /fileadmin/user_upload/index.html successfully created.
Set content to /fileadmin/user_upload/index.html
Fixed permission on /fileadmin/user_upload/index.html.
The following extensions have been added to the generated PackageStates.php file: core, scheduler, extbase, fluid, frontend, fluid_styled_content, filelist, impexp, form, install, recordlist, backend, reports, setup, rte_ckeditor, about, adminpanel, belog, beuser, extensionmanager, felogin, info, redirects, seo, sys_note, t3editor, tstemplate, viewpage
Moving installation to project root
```

**Comment by gilbertsoft** [comment]
I did the same PR for the base dist see https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/pull/19 and https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/issues/10

The problem seems to be related to Windows and DDEV in normal Windows shell, I was able to reproduce the exception here.

Will talk to Helmut about this issue...

**Comment by helhum** [comment]
I'd say this can be closed: https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/pull/19#issuecomment-530409648

**Comment by rfay** [comment]
Ah, I've never tried it except in git bash. Interesting.

**Comment by gilbertsoft** [comment]
I just tested `ddev composer create typo3/cms-base-distribution "^9" --no-interaction --prefer-dist` which works fine in a Windows shel. Git Bash and Power SHel don't have this issue on Windows

**Comment by gilbertsoft** [comment]
Other solution could be `ddev composer create typo3/cms-base-distribution ^^9 --no-interaction --prefer-dist`
Currently searching for an official docu of Microsoft without success. This I have found on excaping: https://www.robvanderwoude.com/escapechars.php

**Comment by rfay** [comment]
I made minor changes here to make it work best with current ddev, and offer the quotes where a `^` is involved. Would appreciate your review @gilbertsoft

**Pull request merged**
