### PR TITLE
Drupal 7: drushrc.php coding standards, fixes #2849

### LINKED ISSUE #2849: Drupal 7: drushrc.php comment coding standards
**Describe the bug**

The drushrc.php file created for Drupal 7 projects doesn't follow coding standards. Example:

```php
<?php
/** #ddev-generated: Automatically generated drushrc.php file (for Drush 8)
 ddev manages this file and may delete or overwrite the file unless this comment is removed.
 Remove this comment if you don't want ddev to manage this file.'
 */
if (getenv('IS_DDEV_PROJECT') == 'true') {
  $options['l'] = "https://project.ddev.site";
}
```

There is no blank line before the file comment, there's no `@file`, the middle lines of the comment are missing `*`, and there's an apostrophe at the end of the comment for some reason.

**To Reproduce**

1. Configure and start a drupal7 DDEV project.
2. A drushrc.php file like above is created in sites/default/

**Expected behavior**

It should be similar to the settings.ddev.php file (truncated example):

```php
<?php

/**
 * @file
 * #ddev-generated: Automatically generated Drupal settings file.
 * ddev manages this file and may delete or overwrite the file unless this
 * comment is removed.
 */

$host = "db";
$port = 3306;
...
```

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: **Windows 10 (2004)**
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop"): **3.2.0**
- ddev version information (use `ddev version`): **v1.17.0-alpha6**

- config.yaml contents

```yaml
name: project
type: drupal7
docroot: ""
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
- project.example.com
mariadb_version: "10.5"
mysql_version: ""
omit_containers: [dba]
use_dns_when_possible: true
composer_version: "2"
```

### PR DESCRIPTION
**Pull request by mbomb007**
## The Problem/Issue/Bug:

[Drupal 7: drushrc.php comment coding standards](https://github.com/drud/ddev/issues/2849)

## How this PR Solves The Problem:

I made the changes to the code writing the drushrc.php file and its doc comment.

## Automated Testing Overview:

No tests were added. Only changes made were to a string.

## Related Issue Link(s):

[Drupal 7: drushrc.php comment coding standards](https://github.com/drud/ddev/issues/2849)

### CODE REVIEW

**Review by rfay — APPROVED** [review]
This looks fine to me. You'll want to test and make sure it really passes muster. You might consider opening this PR in gitpod, https://gitpod.io/#https://github.com/drud/ddev/pull/2850 and run a `make` there and do a `ddev config` on a project to make sure you approve of the drushrc.php that gets created. 

Alternately, download the artifacts from the github builds and just try ddev out with this in it.

**Comment by mbomb007** [comment]
> This looks fine to me. You'll want to test and make sure it really passes muster. You might consider opening this PR in gitpod, https://gitpod.io/#https://github.com/drud/ddev/pull/2850 and run a `make` there and do a `ddev config` on a project to make sure you approve of the drushrc.php that gets created.
> 
> Alternately, download the artifacts from the github builds and just try ddev out with this in it.

How do I run anything like `make` in the workspace? After pulling and running, when I click Open in Gitpod, all I see is an empty screen with `OK`.

**Comment by rfay** [comment]
Thanks for that comment. I'll do a screencast showing how to test a PR. The integration is a little rough still because of both problems in gitpod and immaturity of the approach here. A screencast will help.

Here is the drushrc.php generated for a D7 project in gitpod, if you approve it, this can go in.

```
<?php

/**
 * @file
 * #ddev-generated: Automatically generated drushrc.php file (for Drush 8)
 * ddev manages this file and may delete or overwrite the file unless this comment is removed.
 * Remove this comment if you don't want ddev to manage this file.
 */

if (getenv('IS_DDEV_PROJECT') == 'true') {
  $options['l'] = "https://d7.ddev.site:8443";
}
```

**Comment by mbomb007** [comment]
Yes, this looks great.

**Pull request merged**
