### PR TITLE
Improve apt packages and docs, fixes #4112, fixes #4113, fixes #4125

### LINKED ISSUE #4112: `Unable to locate package certutil` error after running ` sudo apt-get update && sudo apt-get install -y certutil xdg-utils`  - step 14  of ddev wsl2 install
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/therobyouknow/407fe334d59a66d3d3a040edf6d13697

### Current Behavior

`Unable to locate package certutil` error after running ` sudo apt-get update && sudo apt-get install -y certutil xdg-utils`  - step 14 of  https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/ for Windows WSL 2.

### Expected Behavior

No error.

### Steps To Reproduce

Windows 11 WSL2 Ubuntu 20.04, follow steps for Windows WSL2 up to and including step 14 https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/

### Anything else?

_No response_

### LINKED ISSUE #4113: Why are WSL2 and Linux tab ddev install steps different when they both say to install inside distro?
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

_No response_

### Current Behavior

> I have searched the existing issues

- https://github.com/drud/ddev/issues?q=ddev+install+documentation
- https://github.com/drud/ddev/issues?q=ddev.readthedocs.io%2Fen%2Fstable%2Fusers%2Finstall%2Fddev-installation%2F

couldn't see similar issue, so raising this issue.

On "Windows WSL2" tab of https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/  to install ddev it says

> The Windows ddev works fine with the WSL2-based Docker engine. However, the WSL2 ddev setup is vastly preferable and at least 10 times as fast. 

So these are the steps for installing ddev _inside_ the distro running on WSL2:

> 12 Open the WSL2 terminal, for example Ubuntu from the Windows start menu.

> 13 Install ddev with curl -fsSL https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh | bash

There are also steps for installing ddev in Linux - in the Linux tab of the same page https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/

> Debian/Ubuntu and derivative distros - Install the ddev apt repositories with:
> 
> `curl https://apt.fury.io/drud/gpg.key | sudo apt-key add -`
> `echo "deb https://apt.fury.io/drud/ * *" | sudo tee -a /etc/apt/sources.list.d/ddev.list`
> `sudo apt update && sudo apt install -y ddev`

This step, like the step 14 for WSL2, is inside the distro, e.g. running these commands from a shell in Ubuntu.

Why are the steps different?  should we not have a single guide for Linux whether it be a standalone ordinary installation or one running on WSL2?

### Expected Behavior

Why are the steps different?  should we not have a single guide for Linux whether it be a standalone ordinary installation or one running on WSL2?

### Steps To Reproduce

Conpare ddev install steps for Linux with install steps for WSL2 https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/

image

image

image

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

* #4112 
* #4113 
* #4125 

## Release/Deployment notes:

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4133"></a>

### CODE REVIEW

**Comment by rfay** [comment]
@bserem I'd love it if you can review this and also test out the package. You can get it by temporarily 

1. `sudo apt remove ddev`
2. Put `deb [trusted=yes] https://apt.fury.io/rfay-test-org/ /` in your /etc/apt/sources.list.d/ddev.list

This will get a test version pushed up from my fork, v1.20.1-alpha2. You can uninstall and go back to regular settings afterward.

**Comment by bserem** [comment]
@rfay thanks for working on this.

I can verify that it works on my machine. So, that's one off the list!

**Comment by rfay** [comment]
Thanks for testing and for checking this through so carefully. Not sure why I thought it would work as is. Probably because homebrew takes care of those things a bit magically.

**Comment by bserem** [comment]
Anytime!

Apt is a new territory for ddev, things will be ironed out eventually. Personally I'm grateful for the new repo, it makes more sense for Linux systems.

See ya on the next issue

**Pull request merged**
